function ud = sigguitest(fig)
%function ud = create_toolbar(fig)
% CREATE_TOOLBAR Creates the toolbar for the Filter Designer
%

ud = get(fig,'userdata');
ut = uitoolbar(fig);

% MAT-file containing a structure with the cdata for each icon.
load /usr/local/matlab6p5/toolbox/signal/sptoolgui/private/siggui_icons
% uipushtool('cdata',bmp.print,...
%                  'parent',ut,...
%                  'clickedcallback','printcomp(''prnt'')' ,...
%                  'tooltipstring',xlate('Print...'));
% ud.toolbar.printpreview = ...
%     uipushtool('cdata',bmp.printpreview,...
%                  'parent',ut,...
%                  'clickedcallback','printcomp(''prev'')' ,...
%                  'tooltipstring',xlate('Print Preview...'));
ud.toolbar.mousezoom = ...
    uitoggletool('cdata',bmp.mousezoom,...
                 'separator','on',...
                 'parent',ut,...
                 'clickedcallback','zoom',...
                 'tooltipstring',xlate('Mouse Zoom'));
             
ud.toolbar.fullview = ...
    uipushtool('cdata',bmp.fullview,...
                 'parent',ut,...
                 'clickedcallback','axis auto',...
                 'tooltipstring',xlate('Full View (zooms out both axes)')); 
ud.toolbar.zoominy = ...
    uipushtool('cdata',bmp.zoominy,...
                 'parent',ut,...
                 'clickedcallback','filtdes1(''zoom'',''zoominy'')',...
                 'tooltipstring',xlate('Zoom In - Y (vertical axis)'));
ud.toolbar.zoomouty = ...
    uipushtool('cdata',bmp.zoomouty,...
                 'parent',ut,...
                 'clickedcallback','filtdes1(''zoom'',''zoomouty'')',...
                 'tooltipstring',xlate('Zoom Out - Y (vertical axis)'));
ud.toolbar.zoominx = ...
    uipushtool('cdata',bmp.zoominx,...
                 'parent',ut,...
                 'clickedcallback','filtdes1(''zoom'',''zoominx'')',...
                 'tooltipstring',xlate('Zoom In - X (horizontal axis)'));
ud.toolbar.zoomoutx = ...
    uipushtool('cdata',bmp.zoomoutx,...
                 'parent',ut,...
                 'clickedcallback','filtdes1(''zoom'',''zoomoutx'')',...
                 'tooltipstring',xlate('Zoom Out - X (horizontal axis)'));
% ud.toolbar.passband = ...
%     uipushtool('cdata',bmp.passband,...
%                  'parent',ut,...
%                  'clickedcallback','filtdes(''zoom'',''passband'')',...
%                  'tooltipstring',xlate('Passband View (zooms in on Passband)')); 
% ud.toolbar.overlay = ...
%     uipushtool('cdata',bmp.overlay,...
%                  'parent',ut,...
%                  'separator','on',...
%                  'clickedcallback','filtdes(''overlay'')',...
%                  'tooltipstring',xlate('Overlay Spectrum...'));
% ud.toolbar.whatsthis = ...
%     uitoggletool('cdata',bmp.whatsthis,...
%                  'parent',ut,...
%                  'clickedcallback','filtdes(''help'')' ,...
%                  'tooltipstring',xlate('"What''s This?" Help'));
             


set(fig,'userdata',ud);
