% Set up Clear menu
Clear_menu = uimenu(gcf,'Label','Clear','Position',3);

% Define Clear menu functions
Clear_File = uimenu(Clear_menu,'Label','Current File','CallBack',['clear Selected_Trace_no Selected_psk Trace_nos SPIKES trace Temp_filename_raw Raw_traces; cla; legend('''');',...
    'Trace_no_listbox = uicontrol(gcf,''Style'',''listbox'',''Position'', [900 235 300 400],''String'','''',''BackgroundColor'',[1 1 1]);',...
    'uicontrol(gcf,''Style'',''frame'',''Position'',[10 410 100 25],''String'','''',''BackgroundColor'',[1 1 1]);',...
    'uicontrol(gcf,''Style'',''frame'',''Position'',[10 335 100 25],''String'','''',''BackgroundColor'',[1 1 1]);',...
    'uicontrol(gcf,''Style'',''frame'',''Position'',[10 260 100 25],''String'','''',''BackgroundColor'',[1 1 1]);',...
    'subplot(10,10,[1:7,11:17,21:27,31:37,41:47,51:57,61:67,71:77,81:87]); cla;',...
    'if exist(''FindSpikes_userinpt'') == 1,',...
    'uicontrol(gcf,''Style'',''frame'',''Position'',[10 185 100 25],''BackgroundColor'',[1 1 1]); end;']);
Clear_Spike_Set = uimenu(Clear_menu,'Label','Current Spike Set','CallBack',...
    ['cla;',...
     'clear SPIKES SPIKE_TIMES Selected_psk;',...
     'uicontrol(gcf,''Style'',''listbox'',''Max'',2,''Position'', [900 235 300 400],''BackgroundColor'',[1 1 1]);',...
     'uicontrol(gcf,''Style'',''frame'',''Position'',[10 185 100 25],''BackgroundColor'',[1 1 1])']);
Clear_Traces = uimenu(Clear_menu,'Label','Current Traces','CallBack',...
    ['cla;',...
     'clear Temp_filename_raw Trace_nos_cell;',...
     'uicontrol(gcf,''Style'',''listbox'',''Max'',2,''Position'', [900 235 300 400],''BackgroundColor'',[1 1 1]);',...
     'uicontrol(gcf,''Style'',''frame'',''Position'',[10 335 100 25],''BackgroundColor'',[1 1 1]);',...
     'uicontrol(gcf,''Style'',''frame'',''Position'',[10 260 100 25],''BackgroundColor'',[1 1 1]);',...
     'if exist(''FindSpikes_userinpt'') == 1,',...
     'clear SPIKES SPIKE_TIMES;',...
     'uicontrol(gcf,''Style'',''frame'',''Position'',[10 185 100 25],''BackgroundColor'',[1 1 1]); end;',...
     'Clear_Trace = 1;']);


