PlayTraces_parameters = {'Enter Trace number:'};
PlayTraces_dialogbox_title = 'Listen to Spikes dialog box';
PlayTraces_button_exe = uicontrol(gcf,'Style','pushbutton','Position',[10 560 100 25],...
    'String','Play Traces','CallBack',...
    ['Decimate_Spikes = decimate(Temp_filename_raw,8);,'...
    'PlayTraces_userinpt = inputdlg(PlayTraces_parameters,PlayTraces_dialogbox_title);;,'...
    'PlayTraces_char = char(PlayTraces_userinpt(1));; PlayTraces_num = str2num(PlayTraces_char);;,'...
    'soundsc(Temp_filename_raw(:,PlayTraces_num));comet(Decimate_Spikes)']);