% LoadTraces function
LoadTraces_parameters = {'Enter Filename:',...
        'Enter Trace(s): (You can enter a continuous range of traces (1:50), single, noncontiguous traces (1 25 50), a range of noncontiguous traces (1:5:50), or a combination of all three (1:10 15 20 25:5:50)',...
        'Enter Channel(s):','Enter Sampling Frequency (kHz)'};
LoadTraces_dialogbox_title = 'Load Traces dialog box';
LoadTraces_button_exe = uicontrol(gcf,'Style','pushbutton','Position',[10 610 100 25],...
    'String','Load Traces','CallBack',...
    ['LoadTraces_Type_userinpt = {''PCDX'',''GENESIS'',''NeuroSage'',''Text''};,'...
    '[LoadTraces_Type_sel, OK] = listdlg(''PromptString'', ''Select Trace Type:'','...
    '''SelectionMode'', ''single'',''ListString'',LoadTraces_Type_userinpt,''ListSize'',[150 100]);,'...
    'if LoadTraces_Type_sel == 1,'... 
    'if exist(''Clear_Trace'') == 1,'...
    'get_pcdx_file_defAns = {[pcdx_pathname,pcdx_filename],'''',char(LoadTraces_userinpt(3)),char(LoadTraces_userinpt(4))};,'...
    'else [pcdx_filename,pcdx_pathname, pcdx_filterindex] = uigetfile(''*.all'', ''Select a .all file'');,'...
    'get_pcdx_file_defAns = {[pcdx_pathname,pcdx_filename],'''','''',''10''}; end;,'...
    'LoadTraces_userinpt = inputdlg(LoadTraces_parameters,LoadTraces_dialogbox_title,1,get_pcdx_file_defAns);,'...
    'LoadTraces_userinpt_spaces = findstr(char(LoadTraces_userinpt(2)),'' '');,'...
    'parse_LoadTraces(LoadTraces_userinpt); global Temp_filename_raw,'...
    '[Temp_filename_raw] = load_PCDX_SE(char(LoadTraces_userinpt(1,1)),LoadTraces_str,str2num(char(LoadTraces_userinpt(3,1))));;,'...
    'Samp_freq_cell_char_conv = char(LoadTraces_userinpt(4,1)); Samp_freq_char_num_conv_ms = (str2num(Samp_freq_cell_char_conv)*1000)/1000;,'...
    'Temp_filename_raw_xvalues = linspace(1,length(Temp_filename_raw),length(Temp_filename_raw))/Samp_freq_char_num_conv_ms;,'...
    'Temp_filename_raw(:,end+1) = Temp_filename_raw_xvalues'';,'...
    'plot(Temp_filename_raw(:,end),Temp_filename_raw(:,1:end-1),''k''); ylabel(''mV''); xlabel(''ms''); axis auto;,'...
    'subplot(12,10,[111:117]); plot(Temp_filename_raw(:,end),Temp_filename_raw(:,1:end-1),''k''); set(gca,''XTickLabel'',[],''YTickLabel'',[]); hold on,'...
    'subplot(10,10,[1:7,11:17,21:27,31:37,41:47,51:57,61:67,71:77,81:87]);,'...
    'fullview_x = get(gca,''xlim''); fullview_y = get(gca,''ylim'');,'...
    'for i = 1:size(Temp_filename_raw,2)-1,'...
    'if 9.5 > i > 0 Raw_traces(i,:) = [''Trace_'',num2str(i),'' = Temp_filename_raw(:,'',num2str(i),'');  ''];,'...
    'else Raw_traces(i,:) = [''Trace_'',num2str(i),'' = Temp_filename_raw(:,'',num2str(i),'');'']; end;, end;,'...
    'for i = 1:size(Raw_traces,1) eval(Raw_traces(i,:)); end;,'...
    'for i = 1:size(Raw_traces,1),'...
    'if 9.5 > i > 0 Trace_str(i,:) = [''Trace_'',num2str(i),'' '' ];,'...
    'else Trace_str(i,:) = [''Trace_'',num2str(i)];, end; end;,'...
    'for i = 1:size(Trace_str,1) Trace_str_cell{i} = Trace_str(i,:); end;,'...
    'Find_dot_all = findstr(''.all'',char(LoadTraces_userinpt{1}));,'...
    'if isunix == 1,'...
    'if isempty(findstr(''/'',char(LoadTraces_userinpt{1}))) == 1;,'...
    'filename = char(LoadTraces_userinpt{1});,'...
    'else Find_last_linux_slash = max(findstr(''/'',char(LoadTraces_userinpt{1})));,'...
    'filename = char(LoadTraces_userinpt{1}([Find_last_linux_slash+1:Find_dot_all+3])); end,'...
    'else if isempty(findstr(''\'',char(LoadTraces_userinpt{1}))) == 1;,'...
    'filename = char(LoadTraces_userinpt{1});,'...
    'else Find_last_win_slash = max(findstr(''\'',char(LoadTraces_userinpt{1})));,'...
    'filename = char(LoadTraces_userinpt{1}([Find_last_win_slash+1:Find_dot_all+3])); end,'...
    'end,'...
    'Struct_Filename_cellchar_conv = char(filename);,'...
    'Struct_Filename_char=[Struct_Filename_cellchar_conv,''.name = Struct_Filename_cellchar_conv;''];,'...
    'eval(Struct_Filename_char);,'...    
    'Struct_Filename_Add_Raw_Data= [Struct_Filename_cellchar_conv,''.rawdata = Temp_filename_raw''];,'...
    'eval(Struct_Filename_Add_Raw_Data);,'...
    'Trace_nos = str2num(LoadTraces_str);,'...
    'uicontrol(gcf,''Style'',''text'',''Position'',[10 430 100 25],''String'',''File Loaded:'',''BackgroundColor'',[.8 .8 .8],''FontWeight'',''bold'');'...
    'uicontrol(gcf,''Style'',''frame'',''Position'',[10 410 100 25],''BackgroundColor'',[1 1 1]);,'...
    'uicontrol(gcf,''Style'',''text'',''Position'',[15 419 90 10],''String'',filename,''BackgroundColor'',[1 1 1]);'...
    'uicontrol(gcf,''Style'',''text'',''Position'',[10 355 100 25],''String'',''Traces Loaded:'',''BackgroundColor'',[.8 .8 .8],''FontWeight'',''bold'');'...
    'uicontrol(gcf,''Style'',''frame'',''Position'',[10 335 100 25],''BackgroundColor'',[1 1 1]);,'...
    'uicontrol(gcf,''Style'',''text'',''Position'',[15 344 90 10],''String'',char(LoadTraces_userinpt(2)),''BackgroundColor'',[1 1 1]);'...
    'uicontrol(gcf,''Style'',''text'',''Position'',[10 280 100 25],''String'',''Channel:'',''BackgroundColor'',[.8 .8 .8],''FontWeight'',''bold'');'...
    'uicontrol(gcf,''Style'',''frame'',''Position'',[10 260 100 25],''BackgroundColor'',[1 1 1]);,'...
    'uicontrol(gcf,''Style'',''text'',''Position'',[15 269 90 10],''String'',char(LoadTraces_userinpt(3)),''BackgroundColor'',[1 1 1]);'...
    'uicontrol(gcf,''Style'',''text'',''Position'',[890 230 300 420],''String'',[''Trace Type          Trace Number          Channel Number''],''FontWeight'',''bold'',''FontSize'',10,''BackgroundColor'',[.8 .8 .8]);'...
    'Prev_button = uicontrol(gcf,''Style'',''pushbutton'',''Position'',[900 210 30 25],''String'',''<<'');',...
    'Forward_button = uicontrol(gcf,''Style'',''pushbutton'',''Position'',[930 210 30 25],''String'',''>>'');',...
    'Add_button = uicontrol(gcf,''Style'',''pushbutton'',''Position'',[900 185 30 25],''String'',''+'');',...
    'Remove_button = uicontrol(gcf,''Style'',''pushbutton'',''Position'',[930 185 30 25],''String'',''-'');',...
    'Select_all_button = uicontrol(gcf,''Style'',''pushbutton'',''Position'',[1140 210 60 25],''String'',''Select All'',''CallBack'','...
    '[''set(Trace_no_listbox,''''Value'''',1:size(Trace_nos,2)); plot(Temp_filename_raw(:,end),Temp_filename_raw(:,1:end-1),''''k''''); ylabel(''''mV''''); xlabel(''''ms''''); axis auto'']);,'...
    'Separate_traces_button = uicontrol(gcf,''Style'',''checkbox'',''Position'',[1020 210 120 25],''String'',''Separate Traces'');,'...
    'Trace_no_listbox = uicontrol(gcf,''Style'',''listbox'',''Max'',2,''Position'', [900 235 300 400],''String'',Trace_nos_cell,''BackgroundColor'',[1 1 1],''CallBack'','...
    '[''Selected_Trace_no = get(gco,''''Value'''');,'...
    'if get(Separate_traces_button,''''Value'''') == 1,'...
    'cla; separate_color_traces(Selected_Trace_no); else,'...
    'cla; plot(Temp_filename_raw(:,end),Temp_filename_raw(:,Selected_Trace_no),''''k''''); end;,' ...
    'if strcmp(get(Lock_Axes_menu,''''Checked''''),''''on'''') == 1, axis([x_lim_lock(1) x_lim_lock(2) y_lim_lock(1) y_lim_lock(2)]), end;,'...
    'zoom on; Selected_Trace_no_str = num2str(Selected_Trace_no); legend(Selected_Trace_no_str);'']); zoom off;,'...
    'elseif LoadTraces_Type_sel == 2,'...
    'Load_mult_file_question_box = ''Load Mode'';,'...
    'Load_mult_files = questdlg(''Load multiple files?'',Load_mult_file_question_box,''Yes'',''No '',''Yes''),'...
    'if Load_mult_files == ''No '','...
    '[gen_filename,gen_pathname, gen_filterindex] = uigetfile(''*.bin'', ''Select a .bin file'');,'...
    'get_gen_file_parameters = {''Filename'',''Channel''}; get_gen_file_dlg_title = ''Load GENESIS traces'';,'...
    'get_gen_file_defAns = {gen_filename,''''};,'...
    'get_gen_file_userinpt = inputdlg(get_gen_file_parameters,get_gen_file_dlg_title,1,get_gen_file_defAns);,'...
    'Temp_filename_raw = readgenesis([gen_pathname,char(get_gen_file_userinpt(1))],str2num(char(get_gen_file_userinpt(2))));,'...
    'plot(Temp_filename_raw);,'...
    'elseif Load_mult_files == ''Yes'','... 
    'gen_directory = uigetdir;,'...
    'cd_str = [''cd '',gen_directory]; eval(cd_str); gen_files = dir(fullfile(gen_directory,''*.bin''));',...
    'get_gen_file_parameters = {''Channel''}; get_gen_file_dlg_title = ''Select channel:'';,'...
    'get_gen_file_userinpt = inputdlg(get_gen_file_parameters,get_gen_file_dlg_title);,'...
    'for i = 1:size(gen_files,1),'...
    'Temp_filename_raw(:,i) = readgenesis([gen_directory,''/'',gen_files(i).name],str2num(char(get_gen_file_userinpt(1))));,'...
    'end;',...
    'plot(Temp_filename_raw);,'...
    'end;',...
    'elseif LoadTraces_Type_sel == 3,'...
    'if exist(''Clear_Trace'') == 1,'...
    'get_ns_file_defAns = {[ns_pathname,ns_filename],'''',char(LoadTraces_userinpt(3)),char(LoadTraces_userinpt(4))};,'...
    'else [ns_filename,ns_pathname, ns_filterindex] = uigetfile(''*.data'', ''Select a .data file'');,'...
    'get_ns_file_defAns = {[ns_pathname,ns_filename],'''','''',''10''}; end;,'...
    'LoadTraces_userinpt = inputdlg(LoadTraces_parameters,LoadTraces_dialogbox_title,1,get_ns_file_defAns);,'...
    'LoadTraces_userinpt_spaces = findstr(char(LoadTraces_userinpt(2)),'' '');,'...
    'parse_LoadTraces(LoadTraces_userinpt); global Temp_filename_raw,'...
    'Temp_filename_raw = load_NS_SE(LoadTraces_userinpt{1},str2num(LoadTraces_userinpt{2}),str2num(LoadTraces_userinpt{3}));,'...
    'Samp_freq_cell_char_conv = char(LoadTraces_userinpt(4,1)); Samp_freq_char_num_conv_ms = (str2num(Samp_freq_cell_char_conv)*1000)/1000;,'...
    'Temp_filename_raw_xvalues = linspace(1,length(Temp_filename_raw),length(Temp_filename_raw))/Samp_freq_char_num_conv_ms;,'...
    'Temp_filename_raw(:,end+1) = Temp_filename_raw_xvalues'';,'...
    'plot(Temp_filename_raw(:,end),Temp_filename_raw(:,1:end-1),''k'');ylabel(''mV''); xlabel(''ms''); axis auto;,'...
    'subplot(12,10,[111:117]); plot(Temp_filename_raw(:,end),Temp_filename_raw(:,1:end-1),''k''); set(gca,''XTickLabel'',[],''YTickLabel'',[]); hold on,'...
    'subplot(10,10,[1:7,11:17,21:27,31:37,41:47,51:57,61:67,71:77,81:87]);,'...
    'fullview_x = get(gca,''xlim''); fullview_y = get(gca,''ylim'');,'...
    'for i = 1:size(Temp_filename_raw,2)-1,'...
    'if 9.5 > i > 0 Raw_traces(i,:) = [''Trace_'',num2str(i),'' = Temp_filename_raw(:,'',num2str(i),'');  ''];,'...
    'else Raw_traces(i,:) = [''Trace_'',num2str(i),'' = Temp_filename_raw(:,'',num2str(i),'');'']; end;, end;,'...
    'for i = 1:size(Raw_traces,1) eval(Raw_traces(i,:)); end;,'...
    'for i = 1:size(Raw_traces,1),'...
    'if 9.5 > i > 0 Trace_str(i,:) = [''Trace_'',num2str(i),'' '' ];,'...
    'else Trace_str(i,:) = [''Trace_'',num2str(i)];, end; end;,'...
    'for i = 1:size(Trace_str,1) Trace_str_cell{i} = Trace_str(i,:); end;,'...
    'Find_dot_data = findstr(''.data'',char(LoadTraces_userinpt{1}));,'...
    'if isunix == 1,'...
    'if isempty(findstr(''/'',char(LoadTraces_userinpt{1}))) == 1;,'...
    'filename = char(LoadTraces_userinpt{1});,'...
    'else Find_last_linux_slash = max(findstr(''/'',char(LoadTraces_userinpt{1})));,'...
    'filename = char(LoadTraces_userinpt{1}([Find_last_linux_slash+1:Find_dot_data+4])); end,'...
    'else if isempty(findstr(''\'',char(LoadTraces_userinpt{1}))) == 1;,'...
    'filename = char(LoadTraces_userinpt{1});,'...
    'else Find_last_win_slash = max(findstr(''\'',char(LoadTraces_userinpt{1})));,'...
    'filename = char(LoadTraces_userinpt{1}([Find_last_win_slash+1:Find_dot_data+4])); end,'...
    'end,'...
    'uicontrol(gcf,''Style'',''text'',''Position'',[10 430 100 25],''String'',''File Loaded:'',''BackgroundColor'',[.8 .8 .8],''FontWeight'',''bold'');'...
    'uicontrol(gcf,''Style'',''frame'',''Position'',[10 410 100 25],''BackgroundColor'',[1 1 1]);,'...
    'uicontrol(gcf,''Style'',''text'',''Position'',[15 415 90 15],''String'',filename,''BackgroundColor'',[1 1 1]);'...
    'uicontrol(gcf,''Style'',''text'',''Position'',[10 355 100 25],''String'',''Traces Loaded:'',''BackgroundColor'',[.8 .8 .8],''FontWeight'',''bold'');'...
    'uicontrol(gcf,''Style'',''frame'',''Position'',[10 335 100 25],''BackgroundColor'',[1 1 1]);,'...
    'uicontrol(gcf,''Style'',''text'',''Position'',[15 344 90 10],''String'',char(LoadTraces_userinpt(2)),''BackgroundColor'',[1 1 1]);'...
    'uicontrol(gcf,''Style'',''text'',''Position'',[10 280 100 25],''String'',''Channel:'',''BackgroundColor'',[.8 .8 .8],''FontWeight'',''bold'');'...
    'uicontrol(gcf,''Style'',''frame'',''Position'',[10 260 100 25],''BackgroundColor'',[1 1 1]);,'...
    'uicontrol(gcf,''Style'',''text'',''Position'',[15 269 90 10],''String'',char(LoadTraces_userinpt(3)),''BackgroundColor'',[1 1 1]);'...
    'uicontrol(gcf,''Style'',''text'',''Position'',[890 230 300 420],''String'',[''Trace Type          Trace Number          Channel Number''],''FontWeight'',''bold'',''FontSize'',10,''BackgroundColor'',[.8 .8 .8]);'...
    'Prev_button = uicontrol(gcf,''Style'',''pushbutton'',''Position'',[900 210 30 25],''String'',''<<'');',...
    'Forward_button = uicontrol(gcf,''Style'',''pushbutton'',''Position'',[930 210 30 25],''String'',''>>'');',...
    'Add_button = uicontrol(gcf,''Style'',''pushbutton'',''Position'',[900 185 30 25],''String'',''+'');',...
    'Remove_button = uicontrol(gcf,''Style'',''pushbutton'',''Position'',[930 185 30 25],''String'',''-'');',...
    'Select_all_button = uicontrol(gcf,''Style'',''pushbutton'',''Position'',[1140 210 60 25],''String'',''Select All'',''CallBack'','...
    '[''set(Trace_no_listbox,''''Value'''',Trace_nos); plot(Temp_filename_raw(:,end),Temp_filename_raw(:,1:end-1),''''k''''); ylabel(''''mV''''); xlabel(''''ms''''); axis auto'']);,'...    
    'Trace_no_listbox = uicontrol(gcf,''Style'',''listbox'',''Max'',2,''Position'', [900 235 300 400],''String'',Trace_nos_cell,''BackgroundColor'',[1 1 1],''CallBack'','...
    '[''Selected_Trace_no = get(gco,''''Value'''');,'...
    'if get(Separate_traces_button,''''Value'''') == 1,'...
    'cla; separate_color_traces(Selected_Trace_no); else,'...
    'cla; hold on; plot(Temp_filename_raw(:,end),Temp_filename_raw(:,Selected_Trace_no),''''k''''); ylabel(''''mV''''); xlabel(''''ms''''); axis auto; end;,'...
    'if strcmp(get(Lock_Axes_menu,''''Checked''''),''''on'''') == 1, axis([x_lim_lock(1) x_lim_lock(2) y_lim_lock(1) y_lim_lock(2)]), end;',...
    'zoom on; Selected_Trace_no_str = num2str(Selected_Trace_no); legend(Selected_Trace_no_str);'']); zoom on;,'...
    'end']);


%'Temp_filename_raw = Temp_filename_pre_raw.SE_data; Trace_nos_cell = Temp_filename_pre_raw.SE_text;,'...


% 'Trace_nos_cell_str = [''Trace_nos_cell{'',num2str(i),'',1}= [''''  Raw_Trace                Trace_'''',num2str(i),''''                    Channel_'''',num2str(char(LoadTraces_userinpt{3}))''''];''];,'...
%     'eval(Trace_nos_cell_str),'...    
%     'end;,'...  


% 'Trace_nos_str = [''Trace_nos('',num2str(i),'',1) = str2num(Trace_nos_cell{'',num2str(i),'',1}(34));''];,'...
%     'eval(Trace_nos_str),'...
% 

% 'Trace_nos_cell_str = [''Trace_nos_cell{'',num2str(i),'',1} = [''''  Raw_Trace                Trace_'',num2str(i),''                    Channel_'',num2str(char(LoadTraces_userinpt{3})),'''']''];,'...

% 'Conv_to_array = str2num(LoadTraces_userinpt{2,1});,'...
%     'Trace_nos = Conv_to_array; Trace_nos_cell = num2cell(Trace_nos);,'...
% 
% 
% 'if isempty(findstr(''-'',char(LoadTraces_userinpt{2}))) == 1 & isempty(findstr('':'',char(LoadTraces_userinpt{2}))) == 1;,'...
%     'size_Trace_nos = str2num(LoadTraces_userinpt{2});,'...
%     'for i = 1:max(size_Trace_nos),'...
%     'Trace_nos_cell_str = [''Trace_nos_cell{'',num2str(i),'',1} = [''''  Raw_Trace                Trace_'',num2str(i),''                    Channel_'',num2str(char(LoadTraces_userinpt{3})),''''];,'...
%     'eval(Trace_nos_cell_str),'...    
%     'end;,'...
%     'elseif isempty(findstr(''-'',char(LoadTraces_userinpt{2}))) == 0 & isempty(findstr('':'',char(LoadTraces_userinpt{2}))) == 1;,'...
%     'Replace_dash_with_colon = strrep((LoadTraces_userinpt(2,:)),''-'','':'');,'...
%     'Trace_nos_cell_char_conv = char(Replace_dash_with_colon); Trace_nos = eval(Trace_nos_cell_char_conv);,'...    
%     'Concatenate_Trace_nos = cat(2,Trace_nos(:)); Trace_nos_string = num2str(Concatenate_Trace_nos); legend(Trace_nos_string);'... 
%     'elseif isempty(findstr(''-'',char(LoadTraces_userinpt{2}))) == 1 & isempty(findstr('':'',char(LoadTraces_userinpt{2}))) == 0;,'...
%     'Trace_nos = eval(num2str(char(LoadTraces_userinpt{2}))); Trace_nos_cell = num2cell(Trace_nos); end;'...
%     

%'[separate_color_traces(Selected_Trace_no)]);,'...

%'NS_Channels = str2num(LoadTraces_userinpt{3}); size_NS_channels = size(NS_Channels,2);'...
% 'for i = str2num(LoadTraces_userinpt{3}),',...
%     'channel_str = [''Ch_'',num2str(i),'' = Temp_filename_raw.Ch_'',num2str(i),'';'']; eval(channel_str),'...
%     'end,'...
%     'Trace_nos_cell = {''Raw Trace   Channel 1   Trace 1''};'...
%     

%'for i = NS_Channels(1):NS_channels(end), end,'... 


%     'plot(Ch_4,''k'');,' ...
%     'end']);
%     'Trace_no_listbox = uicontrol(gcf,''Style'',''listbox'',''Max'',2,''Position'', [1160 200 70 400],''String'',Trace_nos_cell,''BackgroundColor'',[1 1 1],''CallBack'','...
%     '[''Selected_Trace_no = get(gco,''''Value'''');,'...
%     'plot(Ch_1,''''k'''');,' ...
%     'if strcmp(get(Lock_Axes_menu,''''Checked''''),''''on'''') == 1, axis([x_lim_lock(1) x_lim_lock(2) y_lim_lock(1) y_lim_lock(2)]), end;',...
%     'zoom on; Selected_Trace_no_str = num2str(Selected_Trace_no); legend(Selected_Trace_no_str);'']); zoom on;,'...
%     'end']);


% LoadTraces_parameters = {'Enter Filename:',...
%         'Enter Trace(s): (You can enter a continuous range of traces (1-50), single, noncontiguous traces (1 25 50), a range of noncontiguous traces (1:5:50), or a combination of all three (1-10 15 20 25:5:50)',...
%         'Enter Channel Number:','Enter Sampling Frequency (Hz)'};
% LoadTraces_dialogbox_title = 'Load Traces dialog box';
% LoadTraces_button_exe = uicontrol(gcf,'Style','pushbutton','Position',[10 650 100 25],...
%     'String','Load Traces','CallBack',...
%     ['LoadTraces_userinpt = inputdlg(LoadTraces_parameters,LoadTraces_dialogbox_title);,'...
%     '[Temp_filename_raw] = loadtracesa(char(LoadTraces_userinpt(1,1)),char(LoadTraces_userinpt(2,1)),str2num(char(LoadTraces_userinpt(3,1))));;,'...
%     'Samp_freq_cell_char_conv = char(LoadTraces_userinpt(4,1)); Samp_freq_char_num_conv_ms = str2num(Samp_freq_cell_char_conv)/1000;,'...
%     'Temp_filename_raw_xvalues = linspace(1,length(Temp_filename_raw),length(Temp_filename_raw))/Samp_freq_char_num_conv_ms;,'...
%     'Temp_filename_raw(:,end+1) = Temp_filename_raw_xvalues'';,'...
%     'plot(Temp_filename_raw(:,end),Temp_filename_raw(:,1:end-1),''k''); ylabel(''mV''); xlabel(''ms''); axis auto;,'...
%     'for i = 1:size(Temp_filename_raw,2)-1,'...
%     'if 9.5 > i > 0 Raw_traces(i,:) = [''Trace_'',num2str(i),'' = Temp_filename_raw(:,'',num2str(i),'');  ''];,'...
%     'else Raw_traces(i,:) = [''Trace_'',num2str(i),'' = Temp_filename_raw(:,'',num2str(i),'');'']; end;, end;,'...
%     'for i = 1:size(Raw_traces,1) eval(Raw_traces(i,:)); end;,'...
%     'for i = 1:size(Raw_traces,1),'...
%     'if 9.5 > i > 0 Trace_str(i,:) = [''Trace_'',num2str(i),'' '' ];,'...
%     'else Trace_str(i,:) = [''Trace_'',num2str(i)];, end; end;,'...
%     'for i = 1:size(Trace_str,1) Graph_strings{i} = Trace_str(i,:); end;,'...
%     'Find_dot_all = findstr(''.all'',char(LoadTraces_userinpt{1}));,'...
%     'if isunix == 1,'...
%     'if isempty(findstr(''/'',char(LoadTraces_userinpt{1}))) == 1;,'...
%     'filename = char(LoadTraces_userinpt{1});,'...
%     'else Find_last_linux_slash = max(findstr(''/'',char(LoadTraces_userinpt{1})));,'...
%     'filename = char(LoadTraces_userinpt{1}([Find_last_linux_slash+1:Find_dot_all+3])); end,'...
%     'else if isempty(findstr(''\'',char(LoadTraces_userinpt{1}))) == 1;,'...
%     'filename = char(LoadTraces_userinpt{1});,'...
%     'else Find_last_win_slash = max(findstr(''\'',char(LoadTraces_userinpt{1})));,'...
%     'filename = char(LoadTraces_userinpt{1}([Find_last_win_slash+1:Find_dot_all+3])); end,'...
%     'end,'...
%     'Struct_Filename_cellchar_conv = char(filename);,'...
%     'Struct_Filename_char=[Struct_Filename_cellchar_conv,''.name = Struct_Filename_cellchar_conv;''];,'...
%     'eval(Struct_Filename_char); ,'...
%     'if isempty(findstr(''-'',char(LoadTraces_userinpt{2}))) == 1 & isempty(findstr('':'',char(LoadTraces_userinpt{2}))) == 1;,'...
%     'Conv_to_array = str2num(LoadTraces_userinpt{2,1});,'...
%     'Trace_nos = Conv_to_array;,'...
%     'elseif isempty(findstr(''-'',char(LoadTraces_userinpt{2}))) == 0 & isempty(findstr('':'',char(LoadTraces_userinpt{2}))) == 1;,'...
%     'Replace_dash_with_colon = strrep((LoadTraces_userinpt(2,:)),''-'','':'');,'...
%     'Trace_nos_cell_char_conv = char(Replace_dash_with_colon); Trace_nos = eval(Trace_nos_cell_char_conv);,'...    
%     'Concatenate_Trace_nos = cat(2,Trace_nos(:)); Trace_nos_string = num2str(Concatenate_Trace_nos); legend(Trace_nos_string);'... 
%     'elseif isempty(findstr(''-'',char(LoadTraces_userinpt{2}))) == 1 & isempty(findstr('':'',char(LoadTraces_userinpt{2}))) == 0;,'...
%     'Trace_nos = eval(num2str(char(LoadTraces_userinpt{2}))); end;'...
%     'Struct_Filename_Add_Raw_Data= [Struct_Filename_cellchar_conv,''.rawdata = Temp_filename_raw''];,'...
%     'eval(Struct_Filename_Add_Raw_Data);,'...
%     'uicontrol(gcf,''Style'',''text'',''Position'',[10 470 100 25],''String'',''File Loaded:'',''BackgroundColor'',[.8 .8 .8],''FontWeight'',''bold'');'...
%     'uicontrol(gcf,''Style'',''frame'',''Position'',[10 450 100 25],''BackgroundColor'',[1 1 1]);,'...
%     'uicontrol(gcf,''Style'',''text'',''Position'',[15 459 90 10],''String'',filename,''BackgroundColor'',[1 1 1]);'...
%     'uicontrol(gcf,''Style'',''text'',''Position'',[10 395 100 25],''String'',''Traces Loaded:'',''BackgroundColor'',[.8 .8 .8],''FontWeight'',''bold'');'...
%     'uicontrol(gcf,''Style'',''frame'',''Position'',[10 375 100 25],''BackgroundColor'',[1 1 1]);,'...
%     'uicontrol(gcf,''Style'',''text'',''Position'',[15 384 90 10],''String'',char(LoadTraces_userinpt(2)),''BackgroundColor'',[1 1 1]);'...
%     'uicontrol(gcf,''Style'',''text'',''Position'',[10 320 100 25],''String'',''Channel:'',''BackgroundColor'',[.8 .8 .8],''FontWeight'',''bold'');'...
%     'uicontrol(gcf,''Style'',''frame'',''Position'',[10 300 100 25],''BackgroundColor'',[1 1 1]);,'...
%     'uicontrol(gcf,''Style'',''text'',''Position'',[15 309 90 10],''String'',char(LoadTraces_userinpt(3)),''BackgroundColor'',[1 1 1]);'...
%     'uicontrol(gcf,''Style'',''text'',''Position'',[1147 200 90 420],''String'',''Trace (s):'',''FontWeight'',''bold'',''FontSize'',10,''BackgroundColor'',[.8 .8 .8]);'...
%     'Trace_no_listbox = uicontrol(gcf,''Style'',''listbox'',''Position'', [1160 200 70 400],''String'',Trace_nos,''BackgroundColor'',[1 1 1],''CallBack'','...
%     '[''Selected_Trace_no = get(gco,''''Value'''');,'...
%     'plot(Temp_filename_raw(:,end),Temp_filename_raw(:,Selected_Trace_no),''''k'''');,' ...
%     'zoom; Selected_Trace_no_str = num2str(Selected_Trace_no); legend(Selected_Trace_no_str);'']);']);