% TO DO
% 
% put black line at 0 for STA,CC,AC
% make offset for CC(graphstring),AC (graphstring),STA(both)
% put in text boxes to the right for CC,AC to let the user know which
% file,traces,channel(s) loaded
% Set up Analysis menu
Analysis_menu = uimenu(gcf,'Label','Analysis','Position',2);

% Define Analysis menu functions

% Averaging
Averaging_menu = uimenu(Analysis_menu,'Label','Averaging');

Burst_Triggered_Averaging_menu = uimenu(Averaging_menu,'Label','Burst Triggered Averaging');

Spike_Triggered_Averaging_parameters = {'Enter Channel # of Analog Signal','Enter Maxlag (ms)','Enter Graph title'};
Spike_Triggered_Averaging_dialogbox_title = 'Spike Triggered Averaging';
Spike_Triggered_Averaging_menu = uimenu(Averaging_menu,'Label','Spike Triggered Averaging','CallBack',...
    ['STA_defAns = {'''','''',''STA_''};,'...
     'STA_userinpt = inputdlg(Spike_Triggered_Averaging_parameters,Spike_Triggered_Averaging_dialogbox_title,1,STA_defAns); cla;,'...
     'if LoadTraces_Type_sel == 1,'...
     'Temp_Analog_Signal = load_PCDX_SE(char(LoadTraces_userinpt(1)),LoadTraces_str,str2num(char(STA_userinpt(1))));,'...
     'elseif LoadTraces_Type_sel == 3,'...
     'Temp_pre_Analog_Signal = load_NS_SE(LoadTraces_userinpt{1},str2num(LoadTraces_userinpt{2}),str2num(char(STA_userinpt(1))),str2num(LoadTraces_userinpt{4}));,'...
     'Temp_Analog_Signal = Temp_filename_pre_raw.SE_data(:,1:end-1); end;,'...
     'cla; axis auto; temp_STA_title = char(STA_userinpt(3)); STA_graph_str = [temp_STA_title,'' = sta_SE(Temp_Analog_Signal,temp_spike_times,str2num(char(STA_userinpt(2))),str2num(char(LoadTraces_userinpt(4))),1);''];eval(STA_graph_str);,'...
     'Graph_str_cell{1,size(Graph_str_cell,2)+1} = char(STA_userinpt(3));,'...
     'uicontrol(gcf,''Style'',''text'',''Position'',[1000 175 90 15],''String'',''Graphs:'',''FontWeight'',''bold'',''FontSize'',10,''BackgroundColor'',[.8 .8 .8]);,'...
     'Graph_str_listbox = uicontrol(gcf,''Style'',''listbox'',''Position'', [900 75 300 100],''String'',Graph_str_cell,''BackgroundColor'',[1 1 1],''CallBack'','...
     '[''Selected_Graph_Value = get(gco,''''Value''''); Selected_Graph_String_1 = get(gco,''''String'''');,'...
     'Selected_Graph_String_2 = Selected_Graph_String_1(Selected_Graph_Value);'...
     'if Selected_Graph_String_2{1,1}(1:3) == ''''ISI'''','...
     'cla; plot_ISI = [''''bar('''',char(Selected_Graph_String_2),''''.hist_x,'''',char(Selected_Graph_String_2),''''.hist_y,''''''''k'''''''')''''];eval(plot_ISI);,'...
     'axis_ISI = [''''axis([0 300 0 max('''',char(Selected_Graph_String_2),''''.hist_y)+10])'''']; eval(axis_ISI),'...
     'y_lim = get(gca,''''ylim'''');,'...
     'mean_str = [''''text(200,.80*y_lim(2),[''''''''mean = '''''''',num2str(eval([char(Selected_Graph_String_2),''''''''.mean''''''''])),'''''''' ms''''''''])''''];eval(mean_str);,'...
     'mode_str = [''''text(200,.75*y_lim(2),[''''''''mode = '''''''',num2str(eval([char(Selected_Graph_String_2),''''''''.mode''''''''])),'''''''' ms''''''''])''''];eval(mode_str);,'...
     'median_str = [''''text(200,.70*y_lim(2),[''''''''median = '''''''',num2str(eval([char(Selected_Graph_String_2),''''''''.median''''''''])),''''''''ms''''''''])''''];eval(median_str);,'...
     'std_str = [''''text(200,.65*y_lim(2),[''''''''std = '''''''',num2str(eval([char(Selected_Graph_String_2),''''''''.std''''''''])),'''''''' ms''''''''])''''];eval(std_str);,'...
     'cv_str = [''''text(200,.60*y_lim(2),[''''''''cv = '''''''',num2str(eval([char(Selected_Graph_String_2),''''''''.cv''''''''])),''''''''d''''''''])''''];eval(cv_str);,'...
     'frequency_str = [''''text(200,.55*y_lim(2),[''''''''frequency = '''''''',num2str(eval([char(Selected_Graph_String_2),''''''''.freq''''''''])),'''''''' Hz''''''''])''''];eval(frequency_str);,'...
     'elseif Selected_Graph_String_2{1,1}(1:4) == ''''PSTH'''','...
     'cla; axis auto; hold on; plot_PSTH = [''''bar('''',char(Selected_Graph_String_2),''''.x,'''',char(Selected_Graph_String_2),''''.y,''''''''k'''''''')''''];eval(plot_PSTH);'...
     'for i = 1:size(temp_spike_times,1), raster_plot_str = [''''plot(temp_spike_times{i,1},i+10+max(eval([char(Selected_Graph_String_2),''''''''.y''''''''])),''''''''ko'''''''',''''''''MarkerSize'''''''',1); hold on''''];eval(raster_plot_str); end;,'...
     'set(gca,''''ylim'''',[0 size(temp_spike_times,1)+11+max(eval([char(Selected_Graph_String_2),''''.y'''']))]);,'...
     'plot_PSTH_bar = [''''plot(['''',char(Selected_Graph_String_2),''''.trigger '''' char(Selected_Graph_String_2),''''.trigger],[0 size(temp_spike_times,1)+11+max(eval([char(Selected_Graph_String_2),''''''''.y'''''''']))],''''''''k'''''''')''''];eval(plot_PSTH_bar);'...
     'elseif Selected_Graph_String_2{1,1}(1:5) == ''''Tr_Av'''','...
     'cla; axis auto; plot_Tr_Av_str = [''''plot('''',char(Selected_Graph_String_2),''''(:,2),'''',char(Selected_Graph_String_2),''''(:,1),''''''''b'''''''')''''];eval(plot_Tr_Av_str); hold on; ylabel(''''uV''''); xlabel(''''ms'''');,'...
     'elseif Selected_Graph_String_2{1,1}(1:3) == ''''STA'''','...
     'cla; axis auto; plot_STA_patch = [''''STA_patch = patch('''',char(Selected_Graph_String_2),''''.CI_bar_x,'''',char(Selected_Graph_String_2),''''.CI_bar_y,''''''''w'''''''')'''']; eval(plot_STA_patch);,'...
     'plot_STA_line = [''''plot('''',char(Selected_Graph_String_2),''''.sta_x,'''',char(Selected_Graph_String_2),''''.sta_y,''''''''k'''''''')'''']; eval(plot_STA_line);,'...
     'set(STA_patch,''''facecolor'''',[.85 .85 .85],''''edgecolor'''',[1 1 1]);,'...
     'elseif Selected_Graph_String_2{1,1}(1:12) == ''''AC_st_vs_st_'''','...
     'cla; axis auto; plot_AC_st_vs_st_patch = [''''AC_st_vs_st_patch = patch('''',char(Selected_Graph_String_2),''''.CI_bar_x,'''',char(Selected_Graph_String_2),''''.CI_bar_y,''''''''w'''''''')'''']; eval(plot_AC_st_vs_st_patch);,'...   
     'set(AC_st_vs_st_patch,''''facecolor'''',[.85 .85 .85],''''edgecolor'''',[1 1 1]);,'...
     'plot_AC_st_vs_st_line = [''''plot('''',char(Selected_Graph_String_2),''''.lags,'''',char(Selected_Graph_String_2),''''.cov,''''''''k'''''''',''''''''LineWidth'''''''',2)'''']; eval(plot_AC_st_vs_st_line);,'...                                                                                                
     'elseif Selected_Graph_String_2{1,1}(1:10) == ''''AC_A_vs_A_'''','...
     'cla; axis auto; plot_AC_A_vs_A_patch = [''''AC_A_vs_A_patch = patch('''',char(Selected_Graph_String_2),''''.CI_bar_x,'''',char(Selected_Graph_String_2),''''.CI_bar_y,''''''''w'''''''')'''']; eval(plot_AC_A_vs_A_patch);,'...   
     'set(AC_A_vs_A_patch,''''facecolor'''',[.85 .85 .85],''''edgecolor'''',[1 1 1]);,'...
     'plot_AC_A_vs_A_line = [''''plot('''',char(Selected_Graph_String_2),''''.lags,'''',char(Selected_Graph_String_2),''''.cov,''''''''k'''''''',''''''''LineWidth'''''''',2)'''']; eval(plot_AC_A_vs_A_line);,'...                                                                                                
     'elseif Selected_Graph_String_2{1,1}(1:10) == ''''CC_A_vs_A_'''','...
     'cla; axis auto; plot_CC_A_vs_A_patch = [''''CC_A_vs_A_patch = patch('''',char(Selected_Graph_String_2),''''.CI_bar_x,'''',char(Selected_Graph_String_2),''''.CI_bar_y,''''''''w'''''''')'''']; eval(plot_CC_A_vs_A_patch);,'...   
     'set(CC_A_vs_A_patch,''''facecolor'''',[.85 .85 .85],''''edgecolor'''',[1 1 1]);,'...
     'plot_CC_A_vs_A_line = [''''plot('''',char(Selected_Graph_String_2),''''.lags,'''',char(Selected_Graph_String_2),''''.cov,''''''''k'''''''',''''''''LineWidth'''''''',2)'''']; eval(plot_CC_A_vs_A_line);,'...                                                                                                
     'elseif Selected_Graph_String_2{1,1}(1:11) == ''''CC_A_vs_st_'''','...
     'cla; axis auto; plot_CC_A_vs_st_patch = [''''CC_A_vs_st_patch = patch('''',char(Selected_Graph_String_2),''''.CI_bar_x,'''',char(Selected_Graph_String_2),''''.CI_bar_y,''''''''w'''''''')'''']; eval(plot_CC_A_vs_st_patch);,'...   
     'set(CC_A_vs_st_patch,''''facecolor'''',[.85 .85 .85],''''edgecolor'''',[1 1 1]);,'...
     'plot_CC_A_vs_st_line = [''''plot('''',char(Selected_Graph_String_2),''''.lags,'''',char(Selected_Graph_String_2),''''.cov,''''''''k'''''''',''''''''LineWidth'''''''',2)'''']; eval(plot_CC_A_vs_st_line); end''])']);                                                                                                

                                                                                     

Trace_Averaging_parameters = {'Enter Title for Graph'};
Trace_Averaging_dialogbox_title = 'Trace Averaging';
Trace_Averaging_menu = uimenu(Averaging_menu,'Label','Trace Averaging','CallBack',...
    ['Trace_Averaging_defAns = {''Tr_Av_''};,'...
     'Trace_Averaging_userinpt = inputdlg(Trace_Averaging_parameters,Trace_Averaging_dialogbox_title,1,Trace_Averaging_defAns);,'...
     'cla; axis auto; temp_Tr_Av_title = char(Trace_Averaging_userinpt(1)); Tr_Av_graph_str = [temp_Tr_Av_title,'' = mean(Temp_filename_raw(:,1:end-1),2);''];eval(Tr_Av_graph_str);,'...
     'Samp_freq_ms = (str2num(char(LoadTraces_userinpt(4))))*1000/1000; Length_trace_str = [''size_temp_Tr_Av = size('',temp_Tr_Av_title,'',1);'']; eval(Length_trace_str);,'...
     'max_temp_Tr_Av = size_temp_Tr_Av/Samp_freq_ms; x_scale_ms = linspace(0,max_temp_Tr_Av,size_temp_Tr_Av)'';Tr_Av_graph_str_2 = [temp_Tr_Av_title,''(:,2) = x_scale_ms;''];eval(Tr_Av_graph_str_2);,'...
     'plot_Tr_Av_str = [''plot('',temp_Tr_Av_title,''(:,2),'',temp_Tr_Av_title,''(:,1),''''b'''')''];eval(plot_Tr_Av_str);ylabel(''uV''); xlabel(''ms''),'...
     'Graph_str_cell{1,size(Graph_str_cell,2)+1} = char(Trace_Averaging_userinpt(1));,'...
     'uicontrol(gcf,''Style'',''text'',''Position'',[1000 175 90 15],''String'',''Graphs:'',''FontWeight'',''bold'',''FontSize'',10,''BackgroundColor'',[.8 .8 .8]);,'...
     'Graph_str_listbox = uicontrol(gcf,''Style'',''listbox'',''Position'', [900 75 300 100],''String'',Graph_str_cell,''BackgroundColor'',[1 1 1],''CallBack'','...
     '[''Selected_Graph_Value = get(gco,''''Value''''); Selected_Graph_String_1 = get(gco,''''String'''');,'...
     'Selected_Graph_String_2 = Selected_Graph_String_1(Selected_Graph_Value);'...
     'if Selected_Graph_String_2{1,1}(1:3) == ''''ISI'''','...
     'cla; plot_ISI = [''''bar('''',char(Selected_Graph_String_2),''''.hist_x,'''',char(Selected_Graph_String_2),''''.hist_y,''''''''k'''''''')''''];eval(plot_ISI);,'...
     'axis_ISI = [''''axis([0 300 0 max('''',char(Selected_Graph_String_2),''''.hist_y)+10])'''']; eval(axis_ISI),'...
     'y_lim = get(gca,''''ylim'''');,'...
     'mean_str = [''''text(200,.80*y_lim(2),[''''''''mean = '''''''',num2str(eval([char(Selected_Graph_String_2),''''''''.mean''''''''])),'''''''' ms''''''''])''''];eval(mean_str);,'...
     'mode_str = [''''text(200,.75*y_lim(2),[''''''''mode = '''''''',num2str(eval([char(Selected_Graph_String_2),''''''''.mode''''''''])),'''''''' ms''''''''])''''];eval(mode_str);,'...
     'median_str = [''''text(200,.70*y_lim(2),[''''''''median = '''''''',num2str(eval([char(Selected_Graph_String_2),''''''''.median''''''''])),''''''''ms''''''''])''''];eval(median_str);,'...
     'std_str = [''''text(200,.65*y_lim(2),[''''''''std = '''''''',num2str(eval([char(Selected_Graph_String_2),''''''''.std''''''''])),'''''''' ms''''''''])''''];eval(std_str);,'...
     'cv_str = [''''text(200,.60*y_lim(2),[''''''''cv = '''''''',num2str(eval([char(Selected_Graph_String_2),''''''''.cv''''''''])),''''''''d''''''''])''''];eval(cv_str);,'...
     'frequency_str = [''''text(200,.55*y_lim(2),[''''''''frequency = '''''''',num2str(eval([char(Selected_Graph_String_2),''''''''.freq''''''''])),'''''''' Hz''''''''])''''];eval(frequency_str);,'...
     'elseif Selected_Graph_String_2{1,1}(1:4) == ''''PSTH'''','...
     'cla; axis auto; hold on; plot_PSTH = [''''bar('''',char(Selected_Graph_String_2),''''.x,'''',char(Selected_Graph_String_2),''''.y,''''''''k'''''''')''''];eval(plot_PSTH);'...
     'for i = 1:size(temp_spike_times,1), raster_plot_str = [''''plot(temp_spike_times{i,1},i+10+max(eval([char(Selected_Graph_String_2),''''''''.y''''''''])),''''''''ko'''''''',''''''''MarkerSize'''''''',1); hold on''''];eval(raster_plot_str); end;,'...
     'set(gca,''''ylim'''',[0 size(temp_spike_times,1)+11+max(eval([char(Selected_Graph_String_2),''''.y'''']))]);,'...
     'plot_PSTH_bar = [''''plot(['''',char(Selected_Graph_String_2),''''.trigger '''' char(Selected_Graph_String_2),''''.trigger],[0 size(temp_spike_times,1)+11+max(eval([char(Selected_Graph_String_2),''''''''.y'''''''']))],''''''''k'''''''')''''];eval(plot_PSTH_bar);'...
     'elseif Selected_Graph_String_2{1,1}(1:5) == ''''Tr_Av'''','...
     'cla; axis auto; plot_Tr_Av_str = [''''plot('''',char(Selected_Graph_String_2),''''(:,2),'''',char(Selected_Graph_String_2),''''(:,1),''''''''b'''''''')''''];eval(plot_Tr_Av_str); hold on; ylabel(''''uV''''); xlabel(''''ms'''');,'...
     'elseif Selected_Graph_String_2{1,1}(1:3) == ''''STA'''','...
     'cla; axis auto; plot_STA_patch = [''''STA_patch = patch('''',char(Selected_Graph_String_2),''''.CI_bar_x,'''',char(Selected_Graph_String_2),''''.CI_bar_y,''''''''w'''''''')'''']; eval(plot_STA_patch);,'...
     'plot_STA_line = [''''plot('''',char(Selected_Graph_String_2),''''.sta_x,'''',char(Selected_Graph_String_2),''''.sta_y,''''''''k'''''''')'''']; eval(plot_STA_line);,'...
     'set(STA_patch,''''facecolor'''',[.85 .85 .85],''''edgecolor'''',[1 1 1]);,'...
     'elseif Selected_Graph_String_2{1,1}(1:12) == ''''AC_st_vs_st_'''','...
     'cla; axis auto; plot_AC_st_vs_st_patch = [''''AC_st_vs_st_patch = patch('''',char(Selected_Graph_String_2),''''.CI_bar_x,'''',char(Selected_Graph_String_2),''''.CI_bar_y,''''''''w'''''''')'''']; eval(plot_AC_st_vs_st_patch);,'...   
     'set(AC_st_vs_st_patch,''''facecolor'''',[.85 .85 .85],''''edgecolor'''',[1 1 1]);,'...
     'plot_AC_st_vs_st_line = [''''plot('''',char(Selected_Graph_String_2),''''.lags,'''',char(Selected_Graph_String_2),''''.cov,''''''''k'''''''',''''''''LineWidth'''''''',2)'''']; eval(plot_AC_st_vs_st_line);,'...                                                                                                
     'elseif Selected_Graph_String_2{1,1}(1:10) == ''''AC_A_vs_A_'''','...
     'cla; axis auto; plot_AC_A_vs_A_patch = [''''AC_A_vs_A_patch = patch('''',char(Selected_Graph_String_2),''''.CI_bar_x,'''',char(Selected_Graph_String_2),''''.CI_bar_y,''''''''w'''''''')'''']; eval(plot_AC_A_vs_A_patch);,'...   
     'set(AC_A_vs_A_patch,''''facecolor'''',[.85 .85 .85],''''edgecolor'''',[1 1 1]);,'...
     'plot_AC_A_vs_A_line = [''''plot('''',char(Selected_Graph_String_2),''''.lags,'''',char(Selected_Graph_String_2),''''.cov,''''''''k'''''''',''''''''LineWidth'''''''',2)'''']; eval(plot_AC_A_vs_A_line);,'...                                                                                             
     'elseif Selected_Graph_String_2{1,1}(1:10) == ''''CC_A_vs_A_'''','...
     'cla; axis auto; plot_CC_A_vs_A_patch = [''''CC_A_vs_A_patch = patch('''',char(Selected_Graph_String_2),''''.CI_bar_x,'''',char(Selected_Graph_String_2),''''.CI_bar_y,''''''''w'''''''')'''']; eval(plot_CC_A_vs_A_patch);,'...   
     'set(CC_A_vs_A_patch,''''facecolor'''',[.85 .85 .85],''''edgecolor'''',[1 1 1]);,'...
     'plot_CC_A_vs_A_line = [''''plot('''',char(Selected_Graph_String_2),''''.lags,'''',char(Selected_Graph_String_2),''''.cov,''''''''k'''''''',''''''''LineWidth'''''''',2)'''']; eval(plot_CC_A_vs_A_line);,'...                                                                                                
     'elseif Selected_Graph_String_2{1,1}(1:11) == ''''CC_A_vs_st_'''','...
     'cla; axis auto; plot_CC_A_vs_st_patch = [''''CC_A_vs_st_patch = patch('''',char(Selected_Graph_String_2),''''.CI_bar_x,'''',char(Selected_Graph_String_2),''''.CI_bar_y,''''''''w'''''''')'''']; eval(plot_CC_A_vs_st_patch);,'...   
     'set(CC_A_vs_st_patch,''''facecolor'''',[.85 .85 .85],''''edgecolor'''',[1 1 1]);,'...
     'plot_CC_A_vs_st_line = [''''plot('''',char(Selected_Graph_String_2),''''.lags,'''',char(Selected_Graph_String_2),''''.cov,''''''''k'''''''',''''''''LineWidth'''''''',2)'''']; eval(plot_CC_A_vs_st_line); end''])']);                                                                                                

                                                                         
     



%%%%% Correlations %%%%%
Correlations_menu = uimenu(Analysis_menu,'Label','Correlations');
Autocorrelation_Analysis_menu = uimenu(Correlations_menu,'Label','Autocorrelation');
AC_A_vs_A_parameters = {'Filename','Traces','Analog Signal Channel','Sampling Frequecy (kHz)','Maxlag (s)','Graph Title:'};
AC_A_vs_A_dialogboxtitle = 'Auto Correlation';
AC_A_vs_A_menu = uimenu(Autocorrelation_Analysis_menu,'Label','Analog Signal','CallBack',...
    ['LoadTraces_Type_userinpt = {''PCDX'',''GENESIS'',''NeuroSage'',''Text''};,'...
     '[LoadTraces_Type_sel, OK] = listdlg(''PromptString'', ''Select Trace Type:'','...
     '''SelectionMode'', ''single'',''ListString'',LoadTraces_Type_userinpt,''ListSize'',[150 100]);,'...
     'if LoadTraces_Type_sel == 1,'... 
     '[pcdx_filename,pcdx_pathname, pcdx_filterindex] = uigetfile(''*.all'', ''Select a .all file'');,'...
     'AC_A_vs_A_defAns = {[pcdx_pathname,pcdx_filename],'''','''','''','''',''AC_A_vs_A_''};,'...
     'AC_A_vs_A_userinpt = inputdlg(AC_A_vs_A_parameters,AC_A_vs_A_dialogboxtitle,1,AC_A_vs_A_defAns);,'...
     'LoadTraces_userinpt = AC_A_vs_A_userinpt; parse_LoadTraces(LoadTraces_userinpt);,'...
     'Temp_Analog_Signal = load_PCDX_SE(char(AC_A_vs_A_userinpt(1)),LoadTraces_str,str2num(char(AC_A_vs_A_userinpt(3))));,'...
     'elseif LoadTraces_Type_sel == 3,'...
     '[pcdx_filename,pcdx_pathname, pcdx_filterindex] = uigetfile(''*.data'', ''Select a .data file'');,'...
     'AC_A_vs_A_defAns = {[pcdx_pathname,pcdx_filename],'''','''','''','''',''AC_A_vs_A_''};,'...
     'AC_A_vs_A_userinpt = inputdlg(AC_A_vs_A_parameters,AC_A_vs_A_dialogboxtitle,1,AC_A_vs_A_defAns);,'...
     'Temp_Analog_pre_Signal = load_NS_SE(char(AC_A_vs_A_userinpt(1)),str2num(char(AC_A_vs_A_userinpt(2))),str2num(char(AC_A_vs_A_userinpt(3))),str2num(char(AC_A_vs_A_userinpt(4))));,'...
     'Temp_Analog_Signal = Temp_Analog_pre_Signal.SE_data(:,1:end-1); end;,'...
     'cla; axis auto; temp_AC_A_vs_A_title = char(AC_A_vs_A_userinpt(6)); AC_A_vs_A_graph_str = [temp_AC_A_vs_A_title,'' = auto_corr_SE(Temp_Analog_Signal,str2num(char(AC_A_vs_A_userinpt(4))),str2num(char(AC_A_vs_A_userinpt(5))));''];eval(AC_A_vs_A_graph_str);,'...
     'Graph_str_cell{1,size(Graph_str_cell,2)+1} = char(AC_A_vs_A_userinpt(6));,'...
     'uicontrol(gcf,''Style'',''text'',''Position'',[1000 175 90 15],''String'',''Graphs:'',''FontWeight'',''bold'',''FontSize'',10,''BackgroundColor'',[.8 .8 .8]);,'...
     'Graph_str_listbox = uicontrol(gcf,''Style'',''listbox'',''Position'', [900 75 300 100],''String'',Graph_str_cell,''BackgroundColor'',[1 1 1],''CallBack'','...
     '[''Selected_Graph_Value = get(gco,''''Value''''); Selected_Graph_String_1 = get(gco,''''String'''');,'...
     'Selected_Graph_String_2 = Selected_Graph_String_1(Selected_Graph_Value);'...
     'if Selected_Graph_String_2{1,1}(1:3) == ''''ISI'''','...
     'cla; plot_ISI = [''''bar('''',char(Selected_Graph_String_2),''''.hist_x,'''',char(Selected_Graph_String_2),''''.hist_y,''''''''k'''''''')''''];eval(plot_ISI);,'...
     'axis_ISI = [''''axis([0 300 0 max('''',char(Selected_Graph_String_2),''''.hist_y)+10])'''']; eval(axis_ISI),'...
     'y_lim = get(gca,''''ylim'''');,'...
     'mean_str = [''''text(200,.80*y_lim(2),[''''''''mean = '''''''',num2str(eval([char(Selected_Graph_String_2),''''''''.mean''''''''])),'''''''' ms''''''''])''''];eval(mean_str);,'...
     'mode_str = [''''text(200,.75*y_lim(2),[''''''''mode = '''''''',num2str(eval([char(Selected_Graph_String_2),''''''''.mode''''''''])),'''''''' ms''''''''])''''];eval(mode_str);,'...
     'median_str = [''''text(200,.70*y_lim(2),[''''''''median = '''''''',num2str(eval([char(Selected_Graph_String_2),''''''''.median''''''''])),''''''''ms''''''''])''''];eval(median_str);,'...
     'std_str = [''''text(200,.65*y_lim(2),[''''''''std = '''''''',num2str(eval([char(Selected_Graph_String_2),''''''''.std''''''''])),'''''''' ms''''''''])''''];eval(std_str);,'...
     'cv_str = [''''text(200,.60*y_lim(2),[''''''''cv = '''''''',num2str(eval([char(Selected_Graph_String_2),''''''''.cv''''''''])),''''''''d''''''''])''''];eval(cv_str);,'...
     'frequency_str = [''''text(200,.55*y_lim(2),[''''''''frequency = '''''''',num2str(eval([char(Selected_Graph_String_2),''''''''.freq''''''''])),'''''''' Hz''''''''])''''];eval(frequency_str);,'...
     'elseif Selected_Graph_String_2{1,1}(1:4) == ''''PSTH'''','...
     'cla; axis auto; hold on; plot_PSTH = [''''bar('''',char(Selected_Graph_String_2),''''.x,'''',char(Selected_Graph_String_2),''''.y,''''''''k'''''''')'''']; eval(plot_PSTH);'...
     'for i = 1:size(temp_spike_times,1), raster_plot_str = [''''plot(temp_spike_times{i,1},i+10+max(eval([char(Selected_Graph_String_2),''''''''.y''''''''])),''''''''ko'''''''',''''''''MarkerSize'''''''',1); hold on''''];eval(raster_plot_str); end;,'...
     'set(gca,''''ylim'''',[0 size(temp_spike_times,1)+11+max(eval([char(Selected_Graph_String_2),''''.y'''']))]);,'...
     'plot_PSTH_bar = [''''plot(['''',char(Selected_Graph_String_2),''''.trigger '''' char(Selected_Graph_String_2),''''.trigger],[0 size(temp_spike_times,1)+11+max(eval([char(Selected_Graph_String_2),''''''''.y'''''''']))],''''''''k'''''''')''''];eval(plot_PSTH_bar);'...
     'elseif Selected_Graph_String_2{1,1}(1:5) == ''''Tr_Av'''','...
     'cla; axis auto; plot_Tr_Av_str = [''''plot('''',char(Selected_Graph_String_2),''''(:,2),'''',char(Selected_Graph_String_2),''''(:,1),''''''''b'''''''')''''];eval(plot_Tr_Av_str); ylabel(''''uV''''); xlabel(''''ms'''');,'...
     'elseif Selected_Graph_String_2{1,1}(1:3) == ''''STA'''','...
     'cla; axis auto; plot_STA_patch = [''''STA_patch = patch('''',char(Selected_Graph_String_2),''''.CI_bar_x,'''',char(Selected_Graph_String_2),''''.CI_bar_y,''''''''w'''''''')'''']; eval(plot_STA_patch);,'...
     'plot_STA_line = [''''plot('''',char(Selected_Graph_String_2),''''.sta_x,'''',char(Selected_Graph_String_2),''''.sta_y,''''''''k'''''''')'''']; eval(plot_STA_line);,'...
     'set(STA_patch,''''facecolor'''',[.85 .85 .85],''''edgecolor'''',[1 1 1]);,'...
     'elseif Selected_Graph_String_2{1,1}(1:12) == ''''AC_st_vs_st_'''','...
     'cla; axis auto; plot_AC_st_vs_st_patch = [''''AC_st_vs_st_patch = patch('''',char(Selected_Graph_String_2),''''.CI_bar_x,'''',char(Selected_Graph_String_2),''''.CI_bar_y,''''''''w'''''''')'''']; eval(plot_AC_st_vs_st_patch);,'...   
     'set(AC_st_vs_st_patch,''''facecolor'''',[.85 .85 .85],''''edgecolor'''',[1 1 1]);,'...
     'plot_AC_st_vs_st_line = [''''plot('''',char(Selected_Graph_String_2),''''.lags,'''',char(Selected_Graph_String_2),''''.cov,''''''''k'''''''',''''''''LineWidth'''''''',2)'''']; eval(plot_AC_st_vs_st_line);,'...                                                                                                
     'elseif Selected_Graph_String_2{1,1}(1:10) == ''''AC_A_vs_A_'''','...
     'cla; axis auto; plot_AC_A_vs_A_patch = [''''AC_A_vs_A_patch = patch('''',char(Selected_Graph_String_2),''''.CI_bar_x,'''',char(Selected_Graph_String_2),''''.CI_bar_y,''''''''w'''''''')'''']; eval(plot_AC_A_vs_A_patch);,'...   
     'set(AC_A_vs_A_patch,''''facecolor'''',[.85 .85 .85],''''edgecolor'''',[1 1 1]);,'...
     'plot_AC_A_vs_A_line = [''''plot('''',char(Selected_Graph_String_2),''''.lags,'''',char(Selected_Graph_String_2),''''.cov,''''''''k'''''''',''''''''LineWidth'''''''',2)'''']; eval(plot_AC_A_vs_A_line);,'...                                                                                                
     'elseif Selected_Graph_String_2{1,1}(1:10) == ''''CC_A_vs_A_'''','...
     'cla; axis auto; plot_CC_A_vs_A_patch = [''''CC_A_vs_A_patch = patch('''',char(Selected_Graph_String_2),''''.CI_bar_x,'''',char(Selected_Graph_String_2),''''.CI_bar_y,''''''''w'''''''')'''']; eval(plot_CC_A_vs_A_patch);,'...   
     'set(CC_A_vs_A_patch,''''facecolor'''',[.85 .85 .85],''''edgecolor'''',[1 1 1]);,'...
     'plot_CC_A_vs_A_line = [''''plot('''',char(Selected_Graph_String_2),''''.lags,'''',char(Selected_Graph_String_2),''''.cov,''''''''k'''''''',''''''''LineWidth'''''''',2)'''']; eval(plot_CC_A_vs_A_line);,'...                                                                                                
     'elseif Selected_Graph_String_2{1,1}(1:11) == ''''CC_A_vs_st_'''','...
     'cla; axis auto; plot_CC_A_vs_st_patch = [''''CC_A_vs_st_patch = patch('''',char(Selected_Graph_String_2),''''.CI_bar_x,'''',char(Selected_Graph_String_2),''''.CI_bar_y,''''''''w'''''''')'''']; eval(plot_CC_A_vs_st_patch);,'...   
     'set(CC_A_vs_st_patch,''''facecolor'''',[.85 .85 .85],''''edgecolor'''',[1 1 1]);,'...
     'plot_CC_A_vs_st_line = [''''plot('''',char(Selected_Graph_String_2),''''.lags,'''',char(Selected_Graph_String_2),''''.cov,''''''''k'''''''',''''''''LineWidth'''''''',2)'''']; eval(plot_CC_A_vs_st_line); end''])']);                                                                                                






AC_st_vs_st_parameters = {'Maxlag (s)','Graph Title:'};
AC_st_vs_st_dialogboxtitle = 'Auto Correlation';
AC_st_vs_st_menu = uimenu(Autocorrelation_Analysis_menu,'Label','Spike Times','CallBack',...
    ['AC_st_vs_st_defAns = {'''',''AC_st_vs_st_''};,'...
     'AC_st_vs_st_userinpt = inputdlg(AC_st_vs_st_parameters,AC_st_vs_st_dialogboxtitle,1,AC_st_vs_st_defAns);,'...
     'temp_delta_times = delta_SE(temp_spike_times,size(Temp_filename_raw,1)/str2num(char(LoadTraces_userinpt(4))),str2num(char(LoadTraces_userinpt(4))));,'...
     'cla; temp_AC_st_vs_st_title = char(AC_st_vs_st_userinpt(2)); AC_st_vs_st_graph_str = [temp_AC_st_vs_st_title,'' = auto_corr_SE(temp_delta_times,str2num(char(LoadTraces_userinpt(4))),str2num(char(AC_st_vs_st_userinpt(1))));''];eval(AC_st_vs_st_graph_str);,'...
     'axis auto; Graph_str_cell{1,size(Graph_str_cell,2)+1} = char(AC_st_vs_st_userinpt(2));,'...
     'uicontrol(gcf,''Style'',''text'',''Position'',[1000 175 90 15],''String'',''Graphs:'',''FontWeight'',''bold'',''FontSize'',10,''BackgroundColor'',[.8 .8 .8]);,'...
     'Graph_str_listbox = uicontrol(gcf,''Style'',''listbox'',''Position'', [900 75 300 100],''String'',Graph_str_cell,''BackgroundColor'',[1 1 1],''CallBack'','...
     '[''Selected_Graph_Value = get(gco,''''Value''''); Selected_Graph_String_1 = get(gco,''''String'''');,'...
     'Selected_Graph_String_2 = Selected_Graph_String_1(Selected_Graph_Value);'...
     'if Selected_Graph_String_2{1,1}(1:3) == ''''ISI'''','...
     'cla; plot_ISI = [''''bar('''',char(Selected_Graph_String_2),''''.hist_x,'''',char(Selected_Graph_String_2),''''.hist_y,''''''''k'''''''')''''];eval(plot_ISI);,'...
     'axis_ISI = [''''axis([0 300 0 max('''',char(Selected_Graph_String_2),''''.hist_y)+10])'''']; eval(axis_ISI),'...
     'y_lim = get(gca,''''ylim'''');,'...
     'mean_str = [''''text(200,.80*y_lim(2),[''''''''mean = '''''''',num2str(eval([char(Selected_Graph_String_2),''''''''.mean''''''''])),'''''''' ms''''''''])''''];eval(mean_str);,'...
     'mode_str = [''''text(200,.75*y_lim(2),[''''''''mode = '''''''',num2str(eval([char(Selected_Graph_String_2),''''''''.mode''''''''])),'''''''' ms''''''''])''''];eval(mode_str);,'...
     'median_str = [''''text(200,.70*y_lim(2),[''''''''median = '''''''',num2str(eval([char(Selected_Graph_String_2),''''''''.median''''''''])),''''''''ms''''''''])''''];eval(median_str);,'...
     'std_str = [''''text(200,.65*y_lim(2),[''''''''std = '''''''',num2str(eval([char(Selected_Graph_String_2),''''''''.std''''''''])),'''''''' ms''''''''])''''];eval(std_str);,'...
     'cv_str = [''''text(200,.60*y_lim(2),[''''''''cv = '''''''',num2str(eval([char(Selected_Graph_String_2),''''''''.cv''''''''])),''''''''d''''''''])''''];eval(cv_str);,'...
     'frequency_str = [''''text(200,.55*y_lim(2),[''''''''frequency = '''''''',num2str(eval([char(Selected_Graph_String_2),''''''''.freq''''''''])),'''''''' Hz''''''''])''''];eval(frequency_str);,'...
     'elseif Selected_Graph_String_2{1,1}(1:4) == ''''PSTH'''','...
     'cla; axis auto; hold on; plot_PSTH = [''''bar('''',char(Selected_Graph_String_2),''''.x,'''',char(Selected_Graph_String_2),''''.y,''''''''k'''''''')'''']; eval(plot_PSTH);'...
     'for i = 1:size(temp_spike_times,1), raster_plot_str = [''''plot(temp_spike_times{i,1},i+10+max(eval([char(Selected_Graph_String_2),''''''''.y''''''''])),''''''''ko'''''''',''''''''MarkerSize'''''''',1); hold on''''];eval(raster_plot_str); end;,'...
     'set(gca,''''ylim'''',[0 size(temp_spike_times,1)+11+max(eval([char(Selected_Graph_String_2),''''.y'''']))]);,'...
     'plot_PSTH_bar = [''''plot(['''',char(Selected_Graph_String_2),''''.trigger '''' char(Selected_Graph_String_2),''''.trigger],[0 size(temp_spike_times,1)+11+max(eval([char(Selected_Graph_String_2),''''''''.y'''''''']))],''''''''k'''''''')''''];eval(plot_PSTH_bar);'...
     'elseif Selected_Graph_String_2{1,1}(1:5) == ''''Tr_Av'''','...
     'cla; axis auto; plot_Tr_Av_str = [''''plot('''',char(Selected_Graph_String_2),''''(:,2),'''',char(Selected_Graph_String_2),''''(:,1),''''''''b'''''''')''''];eval(plot_Tr_Av_str); ylabel(''''uV''''); xlabel(''''ms'''');,'...
     'elseif Selected_Graph_String_2{1,1}(1:3) == ''''STA'''','...
     'cla; axis auto; plot_STA_patch = [''''STA_patch = patch('''',char(Selected_Graph_String_2),''''.CI_bar_x,'''',char(Selected_Graph_String_2),''''.CI_bar_y,''''''''w'''''''')'''']; eval(plot_STA_patch);,'...
     'plot_STA_line = [''''plot('''',char(Selected_Graph_String_2),''''.sta_x,'''',char(Selected_Graph_String_2),''''.sta_y,''''''''k'''''''')'''']; eval(plot_STA_line);,'...
     'set(STA_patch,''''facecolor'''',[.85 .85 .85],''''edgecolor'''',[1 1 1]);,'...
     'elseif Selected_Graph_String_2{1,1}(1:12) == ''''AC_st_vs_st_'''','...
     'cla; axis auto; plot_AC_st_vs_st_patch = [''''AC_st_vs_st_patch = patch('''',char(Selected_Graph_String_2),''''.CI_bar_x,'''',char(Selected_Graph_String_2),''''.CI_bar_y,''''''''w'''''''')'''']; eval(plot_AC_st_vs_st_patch);,'...   
     'set(AC_st_vs_st_patch,''''facecolor'''',[.85 .85 .85],''''edgecolor'''',[1 1 1]);,'...
     'plot_AC_st_vs_st_line = [''''plot('''',char(Selected_Graph_String_2),''''.lags,'''',char(Selected_Graph_String_2),''''.cov,''''''''k'''''''',''''''''LineWidth'''''''',2)'''']; eval(plot_AC_st_vs_st_line);,'...                                                                                                
     'elseif Selected_Graph_String_2{1,1}(1:10) == ''''AC_A_vs_A_'''','...
     'cla; axis auto; plot_AC_A_vs_A_patch = [''''AC_A_vs_A_patch = patch('''',char(Selected_Graph_String_2),''''.CI_bar_x,'''',char(Selected_Graph_String_2),''''.CI_bar_y,''''''''w'''''''')'''']; eval(plot_AC_A_vs_A_patch);,'...   
     'set(AC_A_vs_A_patch,''''facecolor'''',[.85 .85 .85],''''edgecolor'''',[1 1 1]);,'...
     'plot_AC_A_vs_A_line = [''''plot('''',char(Selected_Graph_String_2),''''.lags,'''',char(Selected_Graph_String_2),''''.cov,''''''''k'''''''',''''''''LineWidth'''''''',2)'''']; eval(plot_AC_A_vs_A_line);,'...                                                                                                
     'elseif Selected_Graph_String_2{1,1}(1:10) == ''''CC_A_vs_A_'''','...
     'cla; axis auto; plot_CC_A_vs_A_patch = [''''CC_A_vs_A_patch = patch('''',char(Selected_Graph_String_2),''''.CI_bar_x,'''',char(Selected_Graph_String_2),''''.CI_bar_y,''''''''w'''''''')'''']; eval(plot_CC_A_vs_A_patch);,'...   
     'set(CC_A_vs_A_patch,''''facecolor'''',[.85 .85 .85],''''edgecolor'''',[1 1 1]);,'...
     'plot_CC_A_vs_A_line = [''''plot('''',char(Selected_Graph_String_2),''''.lags,'''',char(Selected_Graph_String_2),''''.cov,''''''''k'''''''',''''''''LineWidth'''''''',2)'''']; eval(plot_CC_A_vs_A_line);,'...                                                                                               
     'elseif Selected_Graph_String_2{1,1}(1:11) == ''''CC_A_vs_st_'''','...
     'cla; axis auto; plot_CC_A_vs_st_patch = [''''CC_A_vs_st_patch = patch('''',char(Selected_Graph_String_2),''''.CI_bar_x,'''',char(Selected_Graph_String_2),''''.CI_bar_y,''''''''w'''''''')'''']; eval(plot_CC_A_vs_st_patch);,'...   
     'set(CC_A_vs_st_patch,''''facecolor'''',[.85 .85 .85],''''edgecolor'''',[1 1 1]);,'...
     'plot_CC_A_vs_st_line = [''''plot('''',char(Selected_Graph_String_2),''''.lags,'''',char(Selected_Graph_String_2),''''.cov,''''''''k'''''''',''''''''LineWidth'''''''',2)'''']; eval(plot_CC_A_vs_st_line); end''])']);                                                                                                




Crosscorrelation_Analysis_menu = uimenu(Correlations_menu,'Label','Crosscorrelation');
CC_A_vs_A_parameters = {'Filename','Traces','Source Signal Channel','Target Signal Channel','Sampling Frequecy (kHz)','Maxlag (s)','Graph Title:'};
CC_A_vs_A_dialogboxtitle = 'Cross Correlation';
CC_A_vs_A_menu = uimenu(Crosscorrelation_Analysis_menu,'Label','Analog Signal | Analog Signal','CallBack',...
    ['LoadTraces_Type_userinpt = {''PCDX'',''GENESIS'',''NeuroSage'',''Text''};,'...
     '[LoadTraces_Type_sel, OK] = listdlg(''PromptString'', ''Select Trace Type:'','...
     '''SelectionMode'', ''single'',''ListString'',LoadTraces_Type_userinpt,''ListSize'',[150 100]);,'...
     'if LoadTraces_Type_sel == 1,'... 
     '[pcdx_filename,pcdx_pathname, pcdx_filterindex] = uigetfile(''*.all'', ''Select a .all file'');,'...
     'CC_A_vs_A_defAns = {[pcdx_pathname,pcdx_filename],'''','''','''','''','''',''CC_A_vs_A_''};,'...
     'CC_A_vs_A_userinpt = inputdlg(CC_A_vs_A_parameters,CC_A_vs_A_dialogboxtitle,1,CC_A_vs_A_defAns);,'...
     'LoadTraces_userinpt = CC_A_vs_A_userinpt; parse_LoadTraces(LoadTraces_userinpt);,'...
     'Temp_Analog_Signal_1 = load_PCDX_SE(char(CC_A_vs_A_userinpt(1)),LoadTraces_str,str2num(char(CC_A_vs_A_userinpt(3))));,'...
     'Temp_Analog_Signal_2 = load_PCDX_SE(char(CC_A_vs_A_userinpt(1)),LoadTraces_str,str2num(char(CC_A_vs_A_userinpt(4))));,'...
     'elseif LoadTraces_Type_sel == 3,'...
     '[pcdx_filename,pcdx_pathname, pcdx_filterindex] = uigetfile(''*.data'', ''Select a .data file'');,'...
     'CC_A_vs_A_defAns = {[pcdx_pathname,pcdx_filename],'''','''','''','''','''',''CC_A_vs_A_''};,'...
     'CC_A_vs_A_userinpt = inputdlg(CC_A_vs_A_parameters,CC_A_vs_A_dialogboxtitle,1,CC_A_vs_A_defAns);,'...
     'Temp_Analog_pre_Signal_1 = load_NS_SE(char(CC_A_vs_A_userinpt(1)),str2num(char(CC_A_vs_A_userinpt(2))),str2num(char(CC_A_vs_A_userinpt(3))),str2num(char(CC_A_vs_A_userinpt(5))));,'...
     'Temp_Analog_Signal_1 = Temp_Analog_pre_Signal_1.SE_data(:,1:end-1);,'...
     'Temp_Analog_pre_Signal_2 = load_NS_SE(char(CC_A_vs_A_userinpt(1)),str2num(char(CC_A_vs_A_userinpt(2))),str2num(char(CC_A_vs_A_userinpt(4))),str2num(char(CC_A_vs_A_userinpt(5))));,'...
     'Temp_Analog_Signal_2 = Temp_Analog_pre_Signal_2.SE_data(:,1:end-1);end;,'...
     'cla; axis auto; temp_CC_A_vs_A_title = char(CC_A_vs_A_userinpt(7)); CC_A_vs_A_graph_str = [temp_CC_A_vs_A_title,'' = cross_corr_SE(Temp_Analog_Signal_1,Temp_Analog_Signal_2,str2num(char(CC_A_vs_A_userinpt(5))),str2num(char(CC_A_vs_A_userinpt(6))));''];eval(CC_A_vs_A_graph_str);,'...
     'Graph_str_cell{1,size(Graph_str_cell,2)+1} = char(CC_A_vs_A_userinpt(7));,'...
     'uicontrol(gcf,''Style'',''text'',''Position'',[1000 175 90 15],''String'',''Graphs:'',''FontWeight'',''bold'',''FontSize'',10,''BackgroundColor'',[.8 .8 .8]);,'...
     'Graph_str_listbox = uicontrol(gcf,''Style'',''listbox'',''Position'', [900 75 300 100],''String'',Graph_str_cell,''BackgroundColor'',[1 1 1],''CallBack'','...
     '[''Selected_Graph_Value = get(gco,''''Value''''); Selected_Graph_String_1 = get(gco,''''String'''');,'...
     'Selected_Graph_String_2 = Selected_Graph_String_1(Selected_Graph_Value);'...
     'if Selected_Graph_String_2{1,1}(1:3) == ''''ISI'''','...
     'cla; plot_ISI = [''''bar('''',char(Selected_Graph_String_2),''''.hist_x,'''',char(Selected_Graph_String_2),''''.hist_y,''''''''k'''''''')''''];eval(plot_ISI);,'...
     'axis_ISI = [''''axis([0 300 0 max('''',char(Selected_Graph_String_2),''''.hist_y)+10])'''']; eval(axis_ISI),'...
     'y_lim = get(gca,''''ylim'''');,'...
     'mean_str = [''''text(200,.80*y_lim(2),[''''''''mean = '''''''',num2str(eval([char(Selected_Graph_String_2),''''''''.mean''''''''])),'''''''' ms''''''''])''''];eval(mean_str);,'...
     'mode_str = [''''text(200,.75*y_lim(2),[''''''''mode = '''''''',num2str(eval([char(Selected_Graph_String_2),''''''''.mode''''''''])),'''''''' ms''''''''])''''];eval(mode_str);,'...
     'median_str = [''''text(200,.70*y_lim(2),[''''''''median = '''''''',num2str(eval([char(Selected_Graph_String_2),''''''''.median''''''''])),''''''''ms''''''''])''''];eval(median_str);,'...
     'std_str = [''''text(200,.65*y_lim(2),[''''''''std = '''''''',num2str(eval([char(Selected_Graph_String_2),''''''''.std''''''''])),'''''''' ms''''''''])''''];eval(std_str);,'...
     'cv_str = [''''text(200,.60*y_lim(2),[''''''''cv = '''''''',num2str(eval([char(Selected_Graph_String_2),''''''''.cv''''''''])),''''''''d''''''''])''''];eval(cv_str);,'...
     'frequency_str = [''''text(200,.55*y_lim(2),[''''''''frequency = '''''''',num2str(eval([char(Selected_Graph_String_2),''''''''.freq''''''''])),'''''''' Hz''''''''])''''];eval(frequency_str);,'...
     'elseif Selected_Graph_String_2{1,1}(1:4) == ''''PSTH'''','...
     'cla; axis auto; hold on; plot_PSTH = [''''bar('''',char(Selected_Graph_String_2),''''.x,'''',char(Selected_Graph_String_2),''''.y,''''''''k'''''''')'''']; eval(plot_PSTH);'...
     'for i = 1:size(temp_spike_times,1), raster_plot_str = [''''plot(temp_spike_times{i,1},i+10+max(eval([char(Selected_Graph_String_2),''''''''.y''''''''])),''''''''ko'''''''',''''''''MarkerSize'''''''',1); hold on''''];eval(raster_plot_str); end;,'...
     'set(gca,''''ylim'''',[0 size(temp_spike_times,1)+11+max(eval([char(Selected_Graph_String_2),''''.y'''']))]);,'...
     'plot_PSTH_bar = [''''plot(['''',char(Selected_Graph_String_2),''''.trigger '''' char(Selected_Graph_String_2),''''.trigger],[0 size(temp_spike_times,1)+11+max(eval([char(Selected_Graph_String_2),''''''''.y'''''''']))],''''''''k'''''''')''''];eval(plot_PSTH_bar);'...
     'elseif Selected_Graph_String_2{1,1}(1:5) == ''''Tr_Av'''','...
     'cla; axis auto; plot_Tr_Av_str = [''''plot('''',char(Selected_Graph_String_2),''''(:,2),'''',char(Selected_Graph_String_2),''''(:,1),''''''''b'''''''')''''];eval(plot_Tr_Av_str); ylabel(''''uV''''); xlabel(''''ms'''');,'...
     'elseif Selected_Graph_String_2{1,1}(1:3) == ''''STA'''','...
     'cla; axis auto; plot_STA_patch = [''''STA_patch = patch('''',char(Selected_Graph_String_2),''''.CI_bar_x,'''',char(Selected_Graph_String_2),''''.CI_bar_y,''''''''w'''''''')'''']; eval(plot_STA_patch);,'...
     'plot_STA_line = [''''plot('''',char(Selected_Graph_String_2),''''.sta_x,'''',char(Selected_Graph_String_2),''''.sta_y,''''''''k'''''''')'''']; eval(plot_STA_line);,'...
     'set(STA_patch,''''facecolor'''',[.85 .85 .85],''''edgecolor'''',[1 1 1]);,'...
     'elseif Selected_Graph_String_2{1,1}(1:12) == ''''AC_st_vs_st_'''','...
     'cla; axis auto; plot_AC_st_vs_st_patch = [''''AC_st_vs_st_patch = patch('''',char(Selected_Graph_String_2),''''.CI_bar_x,'''',char(Selected_Graph_String_2),''''.CI_bar_y,''''''''w'''''''')'''']; eval(plot_AC_st_vs_st_patch);,'...   
     'set(AC_st_vs_st_patch,''''facecolor'''',[.85 .85 .85],''''edgecolor'''',[1 1 1]);,'...
     'plot_AC_st_vs_st_line = [''''plot('''',char(Selected_Graph_String_2),''''.lags,'''',char(Selected_Graph_String_2),''''.cov,''''''''k'''''''',''''''''LineWidth'''''''',2)'''']; eval(plot_AC_st_vs_st_line);,'...                                                                                                
     'elseif Selected_Graph_String_2{1,1}(1:10) == ''''AC_A_vs_A_'''','...
     'cla; axis auto; plot_AC_A_vs_A_patch = [''''AC_A_vs_A_patch = patch('''',char(Selected_Graph_String_2),''''.CI_bar_x,'''',char(Selected_Graph_String_2),''''.CI_bar_y,''''''''w'''''''')'''']; eval(plot_AC_A_vs_A_patch);,'...   
     'set(AC_A_vs_A_patch,''''facecolor'''',[.85 .85 .85],''''edgecolor'''',[1 1 1]);,'...
     'plot_AC_A_vs_A_line = [''''plot('''',char(Selected_Graph_String_2),''''.lags,'''',char(Selected_Graph_String_2),''''.cov,''''''''k'''''''',''''''''LineWidth'''''''',2)'''']; eval(plot_AC_A_vs_A_line);,'...                                                                                                
     'elseif Selected_Graph_String_2{1,1}(1:10) == ''''CC_A_vs_A_'''','...
     'cla; axis auto; plot_CC_A_vs_A_patch = [''''CC_A_vs_A_patch = patch('''',char(Selected_Graph_String_2),''''.CI_bar_x,'''',char(Selected_Graph_String_2),''''.CI_bar_y,''''''''w'''''''')'''']; eval(plot_CC_A_vs_A_patch);,'...   
     'set(CC_A_vs_A_patch,''''facecolor'''',[.85 .85 .85],''''edgecolor'''',[1 1 1]);,'...
     'plot_CC_A_vs_A_line = [''''plot('''',char(Selected_Graph_String_2),''''.lags,'''',char(Selected_Graph_String_2),''''.cov,''''''''k'''''''',''''''''LineWidth'''''''',2)'''']; eval(plot_CC_A_vs_A_line);,'...                                                                                                
     'elseif Selected_Graph_String_2{1,1}(1:11) == ''''CC_A_vs_st_'''','...
     'cla; axis auto; plot_CC_A_vs_st_patch = [''''CC_A_vs_st_patch = patch('''',char(Selected_Graph_String_2),''''.CI_bar_x,'''',char(Selected_Graph_String_2),''''.CI_bar_y,''''''''w'''''''')'''']; eval(plot_CC_A_vs_st_patch);,'...   
     'set(CC_A_vs_st_patch,''''facecolor'''',[.85 .85 .85],''''edgecolor'''',[1 1 1]);,'...
     'plot_CC_A_vs_st_line = [''''plot('''',char(Selected_Graph_String_2),''''.lags,'''',char(Selected_Graph_String_2),''''.cov,''''''''k'''''''',''''''''LineWidth'''''''',2)'''']; eval(plot_CC_A_vs_st_line); end''])']);                                                                                                


CC_A_vs_st_parameters = {'Analog Signal Channel','Length of Trace (ms)','Maxlag of Correlation (s)','Graph Title:'};
CC_A_vs_st_dialogboxtitle = 'Cross Correlation';
CC_A_vs_st_menu = uimenu(Crosscorrelation_Analysis_menu,'Label','Analog Signal | Spike Times','CallBack',...
    ['if LoadTraces_Type_sel == 1,'... 
     'CC_A_vs_st_defAns = {'''','''','''',''CC_A_vs_st_''};,'...
     'CC_A_vs_st_userinpt = inputdlg(CC_A_vs_st_parameters,CC_A_vs_st_dialogboxtitle,1,CC_A_vs_st_defAns);,'...
     'Temp_Analog_Signal_1 = load_PCDX_SE(char(LoadTraces_userinpt(1)),LoadTraces_str,str2num(char(CC_A_vs_st_userinpt(1))));,'...
     'temp_delta_times = delta_SE(temp_spike_times,str2num(char(CC_A_vs_st_userinpt(2))),str2num(char(LoadTraces_userinpt(4))));,'...
     'cla; axis auto; temp_CC_A_vs_st_title = char(CC_A_vs_st_userinpt(4)); CC_A_vs_st_graph_str = [temp_CC_A_vs_st_title,'' = cross_corr_SE(Temp_Analog_Signal_1,temp_delta_times,str2num(char(LoadTraces_userinpt(4))),str2num(char(CC_A_vs_st_userinpt(3))));''];eval(CC_A_vs_st_graph_str);,'...
     'elseif LoadTraces_Type_sel == 3,'...
     'CC_A_vs_st_defAns = {'''','''','''',''CC_A_vs_st_''};,'...
     'CC_A_vs_st_userinpt = inputdlg(CC_A_vs_st_parameters,CC_A_vs_st_dialogboxtitle,1,CC_A_vs_st_defAns);,'...
     'Temp_Analog_pre_Signal_1 = load_NS_SE(char(LoadTraces_userinpt(1)),LoadTraces_str,str2num(char(CC_A_vs_st_userinpt(1))),str2num(char(LoadTraces_userinpt(4))));,'...
     'Temp_Analog_Signal_1 = Temp_Analog_pre_Signal_1.SE_data(:,1:end-1);,'...
     'temp_delta_times = delta_SE(temp_spike_times,str2num(char(CC_A_vs_st_userinpt(2))),str2num(char(LoadTraces_userinpt(4))));,'...    
     'cla; axis auto; temp_CC_A_vs_st_title = char(CC_A_vs_st_userinpt(4)); CC_A_vs_st_graph_str = [temp_CC_A_vs_st_title,'' = cross_corr_SE(Temp_Analog_Signal_1,temp_delta_times,str2num(char(LoadTraces_userinpt(4))),str2num(char(CC_A_vs_st_userinpt(3))));''];eval(CC_A_vs_st_graph_str);end,'...
     'Graph_str_cell{1,size(Graph_str_cell,2)+1} = char(CC_A_vs_st_userinpt(4));,'...
     'uicontrol(gcf,''Style'',''text'',''Position'',[1000 175 90 15],''String'',''Graphs:'',''FontWeight'',''bold'',''FontSize'',10,''BackgroundColor'',[.8 .8 .8]);,'...
     'Graph_str_listbox = uicontrol(gcf,''Style'',''listbox'',''Position'', [900 75 300 100],''String'',Graph_str_cell,''BackgroundColor'',[1 1 1],''CallBack'','...
     '[''Selected_Graph_Value = get(gco,''''Value''''); Selected_Graph_String_1 = get(gco,''''String'''');,'...
     'Selected_Graph_String_2 = Selected_Graph_String_1(Selected_Graph_Value);'...
     'if Selected_Graph_String_2{1,1}(1:3) == ''''ISI'''','...
     'cla; plot_ISI = [''''bar('''',char(Selected_Graph_String_2),''''.hist_x,'''',char(Selected_Graph_String_2),''''.hist_y,''''''''k'''''''')''''];eval(plot_ISI);,'...
     'axis_ISI = [''''axis([0 300 0 max('''',char(Selected_Graph_String_2),''''.hist_y)+10])'''']; eval(axis_ISI),'...
     'y_lim = get(gca,''''ylim'''');,'...
     'mean_str = [''''text(200,.80*y_lim(2),[''''''''mean = '''''''',num2str(eval([char(Selected_Graph_String_2),''''''''.mean''''''''])),'''''''' ms''''''''])''''];eval(mean_str);,'...
     'mode_str = [''''text(200,.75*y_lim(2),[''''''''mode = '''''''',num2str(eval([char(Selected_Graph_String_2),''''''''.mode''''''''])),'''''''' ms''''''''])''''];eval(mode_str);,'...
     'median_str = [''''text(200,.70*y_lim(2),[''''''''median = '''''''',num2str(eval([char(Selected_Graph_String_2),''''''''.median''''''''])),''''''''ms''''''''])''''];eval(median_str);,'...
     'std_str = [''''text(200,.65*y_lim(2),[''''''''std = '''''''',num2str(eval([char(Selected_Graph_String_2),''''''''.std''''''''])),'''''''' ms''''''''])''''];eval(std_str);,'...
     'cv_str = [''''text(200,.60*y_lim(2),[''''''''cv = '''''''',num2str(eval([char(Selected_Graph_String_2),''''''''.cv''''''''])),''''''''d''''''''])''''];eval(cv_str);,'...
     'frequency_str = [''''text(200,.55*y_lim(2),[''''''''frequency = '''''''',num2str(eval([char(Selected_Graph_String_2),''''''''.freq''''''''])),'''''''' Hz''''''''])''''];eval(frequency_str);,'...
     'elseif Selected_Graph_String_2{1,1}(1:4) == ''''PSTH'''','...
     'cla; axis auto; hold on; plot_PSTH = [''''bar('''',char(Selected_Graph_String_2),''''.x,'''',char(Selected_Graph_String_2),''''.y,''''''''k'''''''')'''']; eval(plot_PSTH);'...
     'for i = 1:size(temp_spike_times,1), raster_plot_str = [''''plot(temp_spike_times{i,1},i+10+max(eval([char(Selected_Graph_String_2),''''''''.y''''''''])),''''''''ko'''''''',''''''''MarkerSize'''''''',1); hold on''''];eval(raster_plot_str); end;,'...
     'set(gca,''''ylim'''',[0 size(temp_spike_times,1)+11+max(eval([char(Selected_Graph_String_2),''''.y'''']))]);,'...
     'plot_PSTH_bar = [''''plot(['''',char(Selected_Graph_String_2),''''.trigger '''' char(Selected_Graph_String_2),''''.trigger],[0 size(temp_spike_times,1)+11+max(eval([char(Selected_Graph_String_2),''''''''.y'''''''']))],''''''''k'''''''')''''];eval(plot_PSTH_bar);'...
     'elseif Selected_Graph_String_2{1,1}(1:5) == ''''Tr_Av'''','...
     'cla; axis auto; plot_Tr_Av_str = [''''plot('''',char(Selected_Graph_String_2),''''(:,2),'''',char(Selected_Graph_String_2),''''(:,1),''''''''b'''''''')''''];eval(plot_Tr_Av_str); ylabel(''''uV''''); xlabel(''''ms'''');,'...
     'elseif Selected_Graph_String_2{1,1}(1:3) == ''''STA'''','...
     'cla; axis auto; plot_STA_patch = [''''STA_patch = patch('''',char(Selected_Graph_String_2),''''.CI_bar_x,'''',char(Selected_Graph_String_2),''''.CI_bar_y,''''''''w'''''''')'''']; eval(plot_STA_patch);,'...
     'plot_STA_line = [''''plot('''',char(Selected_Graph_String_2),''''.sta_x,'''',char(Selected_Graph_String_2),''''.sta_y,''''''''k'''''''')'''']; eval(plot_STA_line);,'...
     'set(STA_patch,''''facecolor'''',[.85 .85 .85],''''edgecolor'''',[1 1 1]);,'...
     'elseif Selected_Graph_String_2{1,1}(1:12) == ''''AC_st_vs_st_'''','...
     'cla; axis auto; plot_AC_st_vs_st_patch = [''''AC_st_vs_st_patch = patch('''',char(Selected_Graph_String_2),''''.CI_bar_x,'''',char(Selected_Graph_String_2),''''.CI_bar_y,''''''''w'''''''')'''']; eval(plot_AC_st_vs_st_patch);,'...   
     'set(AC_st_vs_st_patch,''''facecolor'''',[.85 .85 .85],''''edgecolor'''',[1 1 1]);,'...
     'plot_AC_st_vs_st_line = [''''plot('''',char(Selected_Graph_String_2),''''.lags,'''',char(Selected_Graph_String_2),''''.cov,''''''''k'''''''',''''''''LineWidth'''''''',2)'''']; eval(plot_AC_st_vs_st_line);,'...                                                                                                
     'elseif Selected_Graph_String_2{1,1}(1:10) == ''''AC_A_vs_A_'''','...
     'cla; axis auto; plot_AC_A_vs_A_patch = [''''AC_A_vs_A_patch = patch('''',char(Selected_Graph_String_2),''''.CI_bar_x,'''',char(Selected_Graph_String_2),''''.CI_bar_y,''''''''w'''''''')'''']; eval(plot_AC_A_vs_A_patch);,'...   
     'set(AC_A_vs_A_patch,''''facecolor'''',[.85 .85 .85],''''edgecolor'''',[1 1 1]);,'...
     'plot_AC_A_vs_A_line = [''''plot('''',char(Selected_Graph_String_2),''''.lags,'''',char(Selected_Graph_String_2),''''.cov,''''''''k'''''''',''''''''LineWidth'''''''',2)'''']; eval(plot_AC_A_vs_A_line);,'...                                                                                                
     'elseif Selected_Graph_String_2{1,1}(1:10) == ''''CC_A_vs_A_'''','...
     'cla; axis auto; plot_CC_A_vs_A_patch = [''''CC_A_vs_A_patch = patch('''',char(Selected_Graph_String_2),''''.CI_bar_x,'''',char(Selected_Graph_String_2),''''.CI_bar_y,''''''''w'''''''')'''']; eval(plot_CC_A_vs_A_patch);,'...   
     'set(CC_A_vs_A_patch,''''facecolor'''',[.85 .85 .85],''''edgecolor'''',[1 1 1]);,'...
     'plot_CC_A_vs_A_line = [''''plot('''',char(Selected_Graph_String_2),''''.lags,'''',char(Selected_Graph_String_2),''''.cov,''''''''k'''''''',''''''''LineWidth'''''''',2)'''']; eval(plot_CC_A_vs_A_line);,'...                                                                                               
     'elseif Selected_Graph_String_2{1,1}(1:11) == ''''CC_A_vs_st_'''','...
     'cla; axis auto; plot_CC_A_vs_st_patch = [''''CC_A_vs_st_patch = patch('''',char(Selected_Graph_String_2),''''.CI_bar_x,'''',char(Selected_Graph_String_2),''''.CI_bar_y,''''''''w'''''''')'''']; eval(plot_CC_A_vs_st_patch);,'...   
     'set(CC_A_vs_st_patch,''''facecolor'''',[.85 .85 .85],''''edgecolor'''',[1 1 1]);,'...
     'plot_CC_A_vs_st_line = [''''plot('''',char(Selected_Graph_String_2),''''.lags,'''',char(Selected_Graph_String_2),''''.cov,''''''''k'''''''',''''''''LineWidth'''''''',2)'''']; eval(plot_CC_A_vs_st_line); end''])']);                                                                                                







%%%%%%%%%%%%%%%%%%%%%%%%

%%% Event Detection %%%%
Event_Detection_menu = uimenu(Analysis_menu,'Label','Event Detection');

Burst_Detection_menu = uimenu(Event_Detection_menu,'Label','Burst Detection (L-S)');

Response_Detection_GLR_parameters = {'Enter Gaussian width (ms):','Length of Signal (ms)','Reference Period ''start:end'',e.g., 0:1000 (ms)','Response Period ''start:end'',e.g., 1000:2500 (ms)','Response Minimal Duration (ms)','Standard Deviation Criterion','Graph Title:'};
Response_Detection_GLR_dialogbox_title = 'Response Detection GLR dialog box';
Response_Detection_GLR_menu = uimenu(Event_Detection_menu,'Label','Response Detection (GLR)','CallBack',...
    ['Response_Detection_GLR_defAns = {'''','''','''','''','''','''',''GLR_RD_''};,'...
     'GLR_RD_userinpt = inputdlg(Response_Detection_GLR_parameters,Response_Detection_GLR_dialogbox_title,1,Response_Detection_GLR_defAns);,'...
     'cla; ref_per = str2num(GLR_RD_userinpt{3}); resp_per = str2num(GLR_RD_userinpt{4});,'...
     'temp_GLR_RD_title = char(GLR_RD_userinpt(7)); GLR_RD_graph_str = [temp_GLR_RD_title,'' = glr_rd_SE(temp_spike_times,str2num(char(GLR_RD_userinpt(1))),str2num(char(LoadTraces_userinpt(4))),str2num(char(GLR_RD_userinpt(2))),1,[ref_per(1) ref_per(end)],[resp_per(1) resp_per(end)],str2num(char(GLR_RD_userinpt(5))),str2num(char(GLR_RD_userinpt(6))));'']; eval(GLR_RD_graph_str);,'...
     'Graph_str_cell{1,size(Graph_str_cell,2)+1} = char(GLR_RD_userinpt(7));,'...
     'uicontrol(gcf,''Style'',''text'',''Position'',[1000 175 90 15],''String'',''Graphs:'',''FontWeight'',''bold'',''FontSize'',10,''BackgroundColor'',[.8 .8 .8]);,'...
     'Graph_str_listbox = uicontrol(gcf,''Style'',''listbox'',''Position'', [900 75 300 100],''String'',Graph_str_cell,''BackgroundColor'',[1 1 1],''CallBack'','...
     '[''Selected_Graph_Value = get(gco,''''Value''''); Selected_Graph_String_1 = get(gco,''''String'''');,'...
     'Selected_Graph_String_2 = Selected_Graph_String_1(Selected_Graph_Value);'...
     'if Selected_Graph_String_2{1,1}(1:3) == ''''ISI'''','...
     'cla; plot_ISI = [''''bar('''',char(Selected_Graph_String_2),''''.hist_x,'''',char(Selected_Graph_String_2),''''.hist_y,''''''''k'''''''')''''];eval(plot_ISI);,'...
     'axis_ISI = [''''axis([0 300 0 max('''',char(Selected_Graph_String_2),''''.hist_y)+10])'''']; eval(axis_ISI),'...
     'y_lim = get(gca,''''ylim'''');,'...
     'mean_str = [''''text(200,.80*y_lim(2),[''''''''mean = '''''''',num2str(eval([char(Selected_Graph_String_2),''''''''.mean''''''''])),'''''''' ms''''''''])''''];eval(mean_str);,'...
     'mode_str = [''''text(200,.75*y_lim(2),[''''''''mode = '''''''',num2str(eval([char(Selected_Graph_String_2),''''''''.mode''''''''])),'''''''' ms''''''''])''''];eval(mode_str);,'...
     'median_str = [''''text(200,.70*y_lim(2),[''''''''median = '''''''',num2str(eval([char(Selected_Graph_String_2),''''''''.median''''''''])),''''''''ms''''''''])''''];eval(median_str);,'...
     'std_str = [''''text(200,.65*y_lim(2),[''''''''std = '''''''',num2str(eval([char(Selected_Graph_String_2),''''''''.std''''''''])),'''''''' ms''''''''])''''];eval(std_str);,'...
     'cv_str = [''''text(200,.60*y_lim(2),[''''''''cv = '''''''',num2str(eval([char(Selected_Graph_String_2),''''''''.cv''''''''])),''''''''d''''''''])''''];eval(cv_str);,'...
     'frequency_str = [''''text(200,.55*y_lim(2),[''''''''frequency = '''''''',num2str(eval([char(Selected_Graph_String_2),''''''''.freq''''''''])),'''''''' Hz''''''''])''''];eval(frequency_str);,'...
     'elseif Selected_Graph_String_2{1,1}(1:4) == ''''PSTH'''','...
     'cla; axis auto; hold on; plot_PSTH = [''''bar('''',char(Selected_Graph_String_2),''''.x,'''',char(Selected_Graph_String_2),''''.y,''''''''k'''''''')'''']; eval(plot_PSTH);'...
     'for i = 1:size(temp_spike_times,1), raster_plot_str = [''''plot(temp_spike_times{i,1},i+10+max(eval([char(Selected_Graph_String_2),''''''''.y''''''''])),''''''''ko'''''''',''''''''MarkerSize'''''''',1); hold on''''];eval(raster_plot_str); end;,'...
     'set(gca,''''ylim'''',[0 size(temp_spike_times,1)+11+max(eval([char(Selected_Graph_String_2),''''.y'''']))]);,'...
     'plot_PSTH_bar = [''''plot(['''',char(Selected_Graph_String_2),''''.trigger '''' char(Selected_Graph_String_2),''''.trigger],[0 size(temp_spike_times,1)+11+max(eval([char(Selected_Graph_String_2),''''''''.y'''''''']))],''''''''k'''''''')''''];eval(plot_PSTH_bar);'...
     'elseif Selected_Graph_String_2{1,1}(1:5) == ''''Tr_Av'''','...
     'cla; axis auto; plot_Tr_Av_str = [''''plot('''',char(Selected_Graph_String_2),''''(:,2),'''',char(Selected_Graph_String_2),''''(:,1),''''''''b'''''''')''''];eval(plot_Tr_Av_str); ylabel(''''uV''''); xlabel(''''ms'''');,'...
     'elseif Selected_Graph_String_2{1,1}(1:3) == ''''STA'''','...
     'cla; axis auto; plot_STA_patch = [''''STA_patch = patch('''',char(Selected_Graph_String_2),''''.CI_bar_x,'''',char(Selected_Graph_String_2),''''.CI_bar_y,''''''''w'''''''')'''']; eval(plot_STA_patch);,'...
     'plot_STA_line = [''''plot('''',char(Selected_Graph_String_2),''''.sta_x,'''',char(Selected_Graph_String_2),''''.sta_y,''''''''k'''''''')'''']; eval(plot_STA_line);,'...
     'set(STA_patch,''''facecolor'''',[.85 .85 .85],''''edgecolor'''',[1 1 1]);,'...
     'elseif Selected_Graph_String_2{1,1}(1:12) == ''''AC_st_vs_st_'''','...
     'cla; axis auto; plot_AC_st_vs_st_patch = [''''AC_st_vs_st_patch = patch('''',char(Selected_Graph_String_2),''''.CI_bar_x,'''',char(Selected_Graph_String_2),''''.CI_bar_y,''''''''w'''''''')'''']; eval(plot_AC_st_vs_st_patch);,'...   
     'set(AC_st_vs_st_patch,''''facecolor'''',[.85 .85 .85],''''edgecolor'''',[1 1 1]);,'...
     'plot_AC_st_vs_st_line = [''''plot('''',char(Selected_Graph_String_2),''''.lags,'''',char(Selected_Graph_String_2),''''.cov,''''''''k'''''''',''''''''LineWidth'''''''',2)'''']; eval(plot_AC_st_vs_st_line);,'...                                                                                                
     'elseif Selected_Graph_String_2{1,1}(1:10) == ''''AC_A_vs_A_'''','...
     'cla; axis auto; plot_AC_A_vs_A_patch = [''''AC_A_vs_A_patch = patch('''',char(Selected_Graph_String_2),''''.CI_bar_x,'''',char(Selected_Graph_String_2),''''.CI_bar_y,''''''''w'''''''')'''']; eval(plot_AC_A_vs_A_patch);,'...   
     'set(AC_A_vs_A_patch,''''facecolor'''',[.85 .85 .85],''''edgecolor'''',[1 1 1]);,'...
     'plot_AC_A_vs_A_line = [''''plot('''',char(Selected_Graph_String_2),''''.lags,'''',char(Selected_Graph_String_2),''''.cov,''''''''k'''''''',''''''''LineWidth'''''''',2)'''']; eval(plot_AC_A_vs_A_line);,'...                                                                                                
     'elseif Selected_Graph_String_2{1,1}(1:10) == ''''CC_A_vs_A_'''','...
     'cla; axis auto; plot_CC_A_vs_A_patch = [''''CC_A_vs_A_patch = patch('''',char(Selected_Graph_String_2),''''.CI_bar_x,'''',char(Selected_Graph_String_2),''''.CI_bar_y,''''''''w'''''''')'''']; eval(plot_CC_A_vs_A_patch);,'...   
     'set(CC_A_vs_A_patch,''''facecolor'''',[.85 .85 .85],''''edgecolor'''',[1 1 1]);,'...
     'plot_CC_A_vs_A_line = [''''plot('''',char(Selected_Graph_String_2),''''.lags,'''',char(Selected_Graph_String_2),''''.cov,''''''''k'''''''',''''''''LineWidth'''''''',2)'''']; eval(plot_CC_A_vs_A_line);,'...                                                                                               
     'elseif Selected_Graph_String_2{1,1}(1:11) == ''''CC_A_vs_st_'''','...
     'cla; axis auto; plot_CC_A_vs_st_patch = [''''CC_A_vs_st_patch = patch('''',char(Selected_Graph_String_2),''''.CI_bar_x,'''',char(Selected_Graph_String_2),''''.CI_bar_y,''''''''w'''''''')'''']; eval(plot_CC_A_vs_st_patch);,'...   
     'set(CC_A_vs_st_patch,''''facecolor'''',[.85 .85 .85],''''edgecolor'''',[1 1 1]);,'...
     'plot_CC_A_vs_st_line = [''''plot('''',char(Selected_Graph_String_2),''''.lags,'''',char(Selected_Graph_String_2),''''.cov,''''''''k'''''''',''''''''LineWidth'''''''',2)'''']; eval(plot_CC_A_vs_st_line);,'...                                                                                                
     'elseif Selected_Graph_String_2{1,1}(1:3) == ''''GLR'''','...
     'end'']);']); 

% 'cla; axis auto; max_gauss_str = [''''max_gauss = max('''',char(Selected_Graph_String_2),''''.gauss_rd(:,1));'''']; eval(max_gauss_str);,'...
%      'plot_GLR_RD = [''''plot('''',char(Selected_Graph_String_2),''''.gauss_rd(:,2),'''',char(Selected_Graph_String_2),''''.gauss_rd(:,1))'''']; hold on; eval(plot_GLR_RD);,'...
%      'plot_GLR_RD_mean_plus_std = [''''plot(['''',char(Selected_Graph_String_2),''''.gauss_rd(1,2) '''',char(Selected_Graph_String_2),''''.gauss_rd(end,2)],['''',char(Selected_Graph_String_2),''''.mean_plus_std '''',char(Selected_Graph_String_2),''''.mean_plus_std],''''''''r'''''''')'''']; eval(plot_GLR_RD_mean_plus_std);,'...
%      'plot_GLR_RD_mean_minus_std = [''''plot(['''',char(Selected_Graph_String_2),''''.gauss_rd(1,2) '''',char(Selected_Graph_String_2),''''.gauss_rd(end,2)],['''',char(Selected_Graph_String_2),''''.mean_minus_std '''',char(Selected_Graph_String_2),''''.mean_minus_std],''''''''r'''''''')'''']; eval(plot_GLR_RD_mean_minus_std);,'...
%      'sig_responses_str = [''''sig_responses = '''',char(Selected_Graph_String_2),''''.stats;'''']; eval(sig_responses_str);,'...
%      'for i = 1:size(sig_responses,1),'...
%      'plot([sig_responses(i,10) sig_responses(i,11)], [max_gauss+.05*max_gauss max_gauss+.05*max_gauss],''''k''''); end,'... 
%      'axis([0 str2num(char(GLR_RD_userinpt{2})) 0 max_gauss + .5*max_gauss]);,'...    
%      'xlabel(''''Time (ms)'''');,'...
%      'ylabel(''''Frequency (Hz)'''');,'...
     

%Selected_Graph_String_2{1,1}(1:7) == ''''GLR_RD_'''','...
     
% for i = 1:size(sig_responses_stats_all,1)
%         plot([sig_responses_stats_all(i,10) sig_responses_stats_all(i,11)], [max_gaussrd+.05*max_gaussrd max_gaussrd+.05*max_gaussrd],'k')
%     end

     
% 'plot_GLR_RD_mean_plus_std = [''''plot(['''',char(Selected_Graph_String_2),''''.gauss_rd(1,2),'''',char(Selected_Graph_String_2),''''.gauss_rd(end,2)''''],['''',char(Selected_Graph_String_2),''''.mean_plus_std,'''',char(Selected_Graph_String_2),''''mean_plus_std],''''''''r'''''''')''''];'


%temp_CC_A_vs_st_title = char(CC_A_vs_st_userinpt(4)); CC_A_vs_st_graph_str = [temp_CC_A_vs_st_title,'' = cross_corr_SE(Temp_Analog_Signal_1,temp_delta_times,str2num(char(LoadTraces_userinpt(4))),str2num(char(CC_A_vs_st_userinpt(3))));''];eval(CC_A_vs_st_graph_str);end,'...

%gauss_tracerd = glr_rd_SE(spike_times, gauss_width, Fs, max_time, flag, reference_period, response_period, min_dur, stdev)
%%%%%%%%%%%%%%%%%%%%%%%%


%%%%% Histograms %%%%%%%
Histograms_menu = uimenu(Analysis_menu,'Label','Histograms');
ISI_Analysis_parameters = {'Enter Binwidth','Enter Title for Graph'};
ISI_Analysis_dialogbox_title = 'ISI Analysis dialog box';
ISI_Analysis_menu = uimenu(Histograms_menu,'Label','ISI Histogram','CallBack',...
   ['ISI_Analysis_defAns = {'''',''ISI_''};,'...
    'ISI_Analysis_userinpt = inputdlg(ISI_Analysis_parameters,ISI_Analysis_dialogbox_title,1,ISI_Analysis_defAns);,'...
    'cla; temp_ISI_title = char(ISI_Analysis_userinpt(2)); ISI_graph_str = [temp_ISI_title,'' = isi_SE(temp_spike_times,str2num(char(ISI_Analysis_userinpt(1))))''];eval(ISI_graph_str);,'...
    'Graph_str_cell{1,size(Graph_str_cell,2)+1} = char(ISI_Analysis_userinpt(2));,'...
    'uicontrol(gcf,''Style'',''text'',''Position'',[1000 175 90 15],''String'',''Graphs:'',''FontWeight'',''bold'',''FontSize'',10,''BackgroundColor'',[.8 .8 .8]);,'...
    'Graph_str_listbox = uicontrol(gcf,''Style'',''listbox'',''Position'', [900 75 300 100],''String'',Graph_str_cell,''BackgroundColor'',[1 1 1],''CallBack'','...
    '[''Selected_Graph_Value = get(gco,''''Value''''); Selected_Graph_String_1 = get(gco,''''String'''');,'...
    'Selected_Graph_String_2 = Selected_Graph_String_1(Selected_Graph_Value);,'...
    'if Selected_Graph_String_2{1,1}(1:3) == ''''ISI'''','...
    'cla; axis auto; plot_ISI = [''''bar('''',char(Selected_Graph_String_2),''''.hist_x,'''',char(Selected_Graph_String_2),''''.hist_y,''''''''k'''''''')''''];eval(plot_ISI);,'...
    'axis_ISI = [''''axis([0 300 0 max('''',char(Selected_Graph_String_2),''''.hist_y)+10])'''']; eval(axis_ISI),'...
    'y_lim = get(gca,''''ylim'''');,'...
    'mean_str = [''''text(200,.80*y_lim(2),[''''''''mean = '''''''',num2str(eval([char(Selected_Graph_String_2),''''''''.mean''''''''])),'''''''' ms''''''''])''''];eval(mean_str);,'...
    'mode_str = [''''text(200,.75*y_lim(2),[''''''''mode = '''''''',num2str(eval([char(Selected_Graph_String_2),''''''''.mode''''''''])),'''''''' ms''''''''])''''];eval(mode_str);,'...
    'median_str = [''''text(200,.70*y_lim(2),[''''''''median = '''''''',num2str(eval([char(Selected_Graph_String_2),''''''''.median''''''''])),''''''''ms''''''''])''''];eval(median_str);,'...
    'std_str = [''''text(200,.65*y_lim(2),[''''''''std = '''''''',num2str(eval([char(Selected_Graph_String_2),''''''''.std''''''''])),'''''''' ms''''''''])''''];eval(std_str);,'...
    'cv_str = [''''text(200,.60*y_lim(2),[''''''''cv = '''''''',num2str(eval([char(Selected_Graph_String_2),''''''''.cv''''''''])),''''''''d''''''''])''''];eval(cv_str);,'...
    'frequency_str = [''''text(200,.55*y_lim(2),[''''''''frequency = '''''''',num2str(eval([char(Selected_Graph_String_2),''''''''.freq''''''''])),'''''''' Hz''''''''])''''];eval(frequency_str);,'...
    'elseif Selected_Graph_String_2{1,1}(1:4) == ''''PSTH'''','...
    'cla; axis auto; hold on; plot_PSTH = [''''bar('''',char(Selected_Graph_String_2),''''.x,'''',char(Selected_Graph_String_2),''''.y,''''''''k'''''''')'''']; eval(plot_PSTH);'...
    'for i = 1:size(temp_spike_times,1), raster_plot_str = [''''plot(temp_spike_times{i,1},i+10+max(eval([char(Selected_Graph_String_2),''''''''.y''''''''])),''''''''ko'''''''',''''''''MarkerSize'''''''',1); hold on''''];eval(raster_plot_str); end;,'...
    'set(gca,''''ylim'''',[0 size(temp_spike_times,1)+11+max(eval([char(Selected_Graph_String_2),''''.y'''']))]);,'...
    'plot_PSTH_bar = [''''plot(['''',char(Selected_Graph_String_2),''''.trigger '''' char(Selected_Graph_String_2),''''.trigger],[0 size(temp_spike_times,1)+11+max(eval([char(Selected_Graph_String_2),''''''''.y'''''''']))],''''''''k'''''''')''''];eval(plot_PSTH_bar);'...
    'elseif Selected_Graph_String_2{1,1}(1:5) == ''''Tr_Av'''','...
    'cla; axis auto; plot_Tr_Av_str = [''''plot('''',char(Selected_Graph_String_2),''''(:,2),'''',char(Selected_Graph_String_2),''''(:,1),''''''''b'''''''')''''];eval(plot_Tr_Av_str); ylabel(''''uV''''); xlabel(''''ms'''');,'...
    'elseif Selected_Graph_String_2{1,1}(1:3) == ''''STA'''','...
    'cla; axis auto; plot_STA_patch = [''''STA_patch = patch('''',char(Selected_Graph_String_2),''''.CI_bar_x,'''',char(Selected_Graph_String_2),''''.CI_bar_y,''''''''w'''''''')'''']; eval(plot_STA_patch);,'...
    'plot_STA_line = [''''plot('''',char(Selected_Graph_String_2),''''.sta_x,'''',char(Selected_Graph_String_2),''''.sta_y,''''''''k'''''''')'''']; eval(plot_STA_line);,'...
    'set(STA_patch,''''facecolor'''',[.85 .85 .85],''''edgecolor'''',[1 1 1]);,'...
    'elseif Selected_Graph_String_2{1,1}(1:12) == ''''AC_st_vs_st_'''','...
    'cla; axis auto; plot_AC_st_vs_st_patch = [''''AC_st_vs_st_patch = patch('''',char(Selected_Graph_String_2),''''.CI_bar_x,'''',char(Selected_Graph_String_2),''''.CI_bar_y,''''''''w'''''''')'''']; eval(plot_AC_st_vs_st_patch);,'...   
    'set(AC_st_vs_st_patch,''''facecolor'''',[.85 .85 .85],''''edgecolor'''',[1 1 1]);,'...
    'plot_AC_st_vs_st_line = [''''plot('''',char(Selected_Graph_String_2),''''.lags,'''',char(Selected_Graph_String_2),''''.cov,''''''''k'''''''',''''''''LineWidth'''''''',2)'''']; eval(plot_AC_st_vs_st_line);,'...                                                                                                
    'elseif Selected_Graph_String_2{1,1}(1:10) == ''''AC_A_vs_A_'''','...
    'cla; axis auto; plot_AC_A_vs_A_patch = [''''AC_A_vs_A_patch = patch('''',char(Selected_Graph_String_2),''''.CI_bar_x,'''',char(Selected_Graph_String_2),''''.CI_bar_y,''''''''w'''''''')'''']; eval(plot_AC_A_vs_A_patch);,'...   
    'set(AC_A_vs_A_patch,''''facecolor'''',[.85 .85 .85],''''edgecolor'''',[1 1 1]);,'...
    'plot_AC_A_vs_A_line = [''''plot('''',char(Selected_Graph_String_2),''''.lags,'''',char(Selected_Graph_String_2),''''.cov,''''''''k'''''''',''''''''LineWidth'''''''',2)'''']; eval(plot_AC_A_vs_A_line);,'...                                                                                              
    'elseif Selected_Graph_String_2{1,1}(1:10) == ''''CC_A_vs_A_'''','...
    'cla; axis auto; plot_CC_A_vs_A_patch = [''''CC_A_vs_A_patch = patch('''',char(Selected_Graph_String_2),''''.CI_bar_x,'''',char(Selected_Graph_String_2),''''.CI_bar_y,''''''''w'''''''')'''']; eval(plot_CC_A_vs_A_patch);,'...   
    'set(CC_A_vs_A_patch,''''facecolor'''',[.85 .85 .85],''''edgecolor'''',[1 1 1]);,'...
    'plot_CC_A_vs_A_line = [''''plot('''',char(Selected_Graph_String_2),''''.lags,'''',char(Selected_Graph_String_2),''''.cov,''''''''k'''''''',''''''''LineWidth'''''''',2)'''']; eval(plot_CC_A_vs_A_line);,'...                                                                                              
    'elseif Selected_Graph_String_2{1,1}(1:11) == ''''CC_A_vs_st_'''','...
    'cla; axis auto; plot_CC_A_vs_st_patch = [''''CC_A_vs_st_patch = patch('''',char(Selected_Graph_String_2),''''.CI_bar_x,'''',char(Selected_Graph_String_2),''''.CI_bar_y,''''''''w'''''''')'''']; eval(plot_CC_A_vs_st_patch);,'...   
    'set(CC_A_vs_st_patch,''''facecolor'''',[.85 .85 .85],''''edgecolor'''',[1 1 1]);,'...
    'plot_CC_A_vs_st_line = [''''plot('''',char(Selected_Graph_String_2),''''.lags,'''',char(Selected_Graph_String_2),''''.cov,''''''''k'''''''',''''''''LineWidth'''''''',2)'''']; eval(plot_CC_A_vs_st_line); end''])']);                                                                                                
    

                                                                                             

PSTH_parameters = {'Enter trial length (ms)','Enter binwidth (ms):','Enter stimulus time (ms):','Enter graph title'};
PSTH_dialogbox_title = 'PSTH dialog box';
PSTH_Analysis_menu = uimenu(Histograms_menu,'Label','PST Histogram','CallBack',...
    ['PSTH_defAns = {'''','''','''',''PSTH_''};,'...
     'PSTH_userinpt = inputdlg(PSTH_parameters,PSTH_dialogbox_title,1,PSTH_defAns); cla; legend off;,'...
     'temp_PSTH_title = char(PSTH_userinpt(4)); PSTH_graph_str = [temp_PSTH_title,'' = psth_rast_SE(temp_spike_times,str2num(char(PSTH_userinpt(1))),str2num(char(PSTH_userinpt(2))),str2num(char(PSTH_userinpt(3))))''];eval(PSTH_graph_str);,'...
     'Graph_str_cell{1,size(Graph_str_cell,2)+1} = char(PSTH_userinpt(4));,'...
     'uicontrol(gcf,''Style'',''text'',''Position'',[1000 175 90 15],''String'',''Graphs:'',''FontWeight'',''bold'',''FontSize'',10,''BackgroundColor'',[.8 .8 .8]);'...
     'Graph_str_listbox = uicontrol(gcf,''Style'',''listbox'',''Position'', [900 75 300 100],''String'',Graph_str_cell,''BackgroundColor'',[1 1 1],''CallBack'','...
     '[''Selected_Graph_Value = get(gco,''''Value''''); Selected_Graph_String_1 = get(gco,''''String'''');,'...
     'Selected_Graph_String_2 = Selected_Graph_String_1(Selected_Graph_Value);'...
     'if Selected_Graph_String_2{1,1}(1:3) == ''''ISI'''','...
     'cla; axis auto; plot_ISI = [''''bar('''',char(Selected_Graph_String_2),''''.hist_x,'''',char(Selected_Graph_String_2),''''.hist_y,''''''''k'''''''')''''];eval(plot_ISI);,'...
     'axis_ISI = [''''axis([0 300 0 max('''',char(Selected_Graph_String_2),''''.hist_y)+10])'''']; eval(axis_ISI),'...
     'y_lim = get(gca,''''ylim'''');,'...
     'mean_str = [''''text(200,.80*y_lim(2),[''''''''mean = '''''''',num2str(eval([char(Selected_Graph_String_2),''''''''.mean''''''''])),'''''''' ms''''''''])''''];eval(mean_str);,'...
     'mode_str = [''''text(200,.75*y_lim(2),[''''''''mode = '''''''',num2str(eval([char(Selected_Graph_String_2),''''''''.mode''''''''])),'''''''' ms''''''''])''''];eval(mode_str);,'...
     'median_str = [''''text(200,.70*y_lim(2),[''''''''median = '''''''',num2str(eval([char(Selected_Graph_String_2),''''''''.median''''''''])),''''''''ms''''''''])''''];eval(median_str);,'...
     'std_str = [''''text(200,.65*y_lim(2),[''''''''std = '''''''',num2str(eval([char(Selected_Graph_String_2),''''''''.std''''''''])),'''''''' ms''''''''])''''];eval(std_str);,'...
     'cv_str = [''''text(200,.60*y_lim(2),[''''''''cv = '''''''',num2str(eval([char(Selected_Graph_String_2),''''''''.cv''''''''])),''''''''d''''''''])''''];eval(cv_str);,'...
     'frequency_str = [''''text(200,.55*y_lim(2),[''''''''frequency = '''''''',num2str(eval([char(Selected_Graph_String_2),''''''''.freq''''''''])),'''''''' Hz''''''''])''''];eval(frequency_str);,'...
     'elseif Selected_Graph_String_2{1,1}(1:4) == ''''PSTH'''','...
     'cla; axis auto; hold on; plot_PSTH = [''''bar('''',char(Selected_Graph_String_2),''''.x,'''',char(Selected_Graph_String_2),''''.y,''''''''k'''''''')''''];eval(plot_PSTH);'...
     'for i = 1:size(temp_spike_times,1), raster_plot_str = [''''plot(temp_spike_times{i,1},i+10+max(eval([char(Selected_Graph_String_2),''''''''.y''''''''])),''''''''ko'''''''',''''''''MarkerSize'''''''',1); hold on''''];eval(raster_plot_str); end;,'...
     'set(gca,''''ylim'''',[0 size(temp_spike_times,1)+11+max(eval([char(Selected_Graph_String_2),''''.y'''']))]);,'...
     'plot_PSTH_bar = [''''plot(['''',char(Selected_Graph_String_2),''''.trigger '''' char(Selected_Graph_String_2),''''.trigger],[0 size(temp_spike_times,1)+11+max(eval([char(Selected_Graph_String_2),''''''''.y'''''''']))],''''''''k'''''''')''''];eval(plot_PSTH_bar);'...
     'elseif Selected_Graph_String_2{1,1}(1:5) == ''''Tr_Av'''','...
     'cla; axis auto; plot_Tr_Av_str = [''''plot('''',char(Selected_Graph_String_2),''''(:,2),'''',char(Selected_Graph_String_2),''''(:,1),''''''''b'''''''')''''];eval(plot_Tr_Av_str); ylabel(''''uV''''); xlabel(''''ms'''');,'...
     'elseif Selected_Graph_String_2{1,1}(1:3) == ''''STA'''','...
     'cla; axis auto; plot_STA_patch = [''''STA_patch = patch('''',char(Selected_Graph_String_2),''''.CI_bar_x,'''',char(Selected_Graph_String_2),''''.CI_bar_y,''''''''w'''''''')'''']; eval(plot_STA_patch);,'...
     'plot_STA_line = [''''plot('''',char(Selected_Graph_String_2),''''.sta_x,'''',char(Selected_Graph_String_2),''''.sta_y,''''''''k'''''''')'''']; eval(plot_STA_line);,'...
     'set(STA_patch,''''facecolor'''',[.85 .85 .85],''''edgecolor'''',[1 1 1]);,'...
     'elseif Selected_Graph_String_2{1,1}(1:12) == ''''AC_st_vs_st_'''','...
     'cla; axis auto; plot_AC_st_vs_st_patch = [''''AC_st_vs_st_patch = patch('''',char(Selected_Graph_String_2),''''.CI_bar_x,'''',char(Selected_Graph_String_2),''''.CI_bar_y,''''''''w'''''''')'''']; eval(plot_AC_st_vs_st_patch);,'...   
     'set(AC_st_vs_st_patch,''''facecolor'''',[.85 .85 .85],''''edgecolor'''',[1 1 1]);,'...
     'plot_AC_st_vs_st_line = [''''plot('''',char(Selected_Graph_String_2),''''.lags,'''',char(Selected_Graph_String_2),''''.cov,''''''''k'''''''',''''''''LineWidth'''''''',2)'''']; eval(plot_AC_st_vs_st_line);,'...                                                                                                
     'elseif Selected_Graph_String_2{1,1}(1:10) == ''''AC_A_vs_A_'''','...
     'cla; axis auto; plot_AC_A_vs_A_patch = [''''AC_A_vs_A_patch = patch('''',char(Selected_Graph_String_2),''''.CI_bar_x,'''',char(Selected_Graph_String_2),''''.CI_bar_y,''''''''w'''''''')'''']; eval(plot_AC_A_vs_A_patch);,'...   
     'set(AC_A_vs_A_patch,''''facecolor'''',[.85 .85 .85],''''edgecolor'''',[1 1 1]);,'...
     'plot_AC_A_vs_A_line = [''''plot('''',char(Selected_Graph_String_2),''''.lags,'''',char(Selected_Graph_String_2),''''.cov,''''''''k'''''''',''''''''LineWidth'''''''',2)'''']; eval(plot_AC_A_vs_A_line);,'...                                                                                                
     'elseif Selected_Graph_String_2{1,1}(1:10) == ''''CC_A_vs_A_'''','...
     'cla; axis auto; plot_CC_A_vs_A_patch = [''''CC_A_vs_A_patch = patch('''',char(Selected_Graph_String_2),''''.CI_bar_x,'''',char(Selected_Graph_String_2),''''.CI_bar_y,''''''''w'''''''')'''']; eval(plot_CC_A_vs_A_patch);,'...   
     'set(CC_A_vs_A_patch,''''facecolor'''',[.85 .85 .85],''''edgecolor'''',[1 1 1]);,'...
     'plot_CC_A_vs_A_line = [''''plot('''',char(Selected_Graph_String_2),''''.lags,'''',char(Selected_Graph_String_2),''''.cov,''''''''k'''''''',''''''''LineWidth'''''''',2)'''']; eval(plot_CC_A_vs_A_line);,'...                                                                                               
     'elseif Selected_Graph_String_2{1,1}(1:11) == ''''CC_A_vs_st_'''','...
     'cla; axis auto; plot_CC_A_vs_st_patch = [''''CC_A_vs_st_patch = patch('''',char(Selected_Graph_String_2),''''.CI_bar_x,'''',char(Selected_Graph_String_2),''''.CI_bar_y,''''''''w'''''''')'''']; eval(plot_CC_A_vs_st_patch);,'...   
     'set(CC_A_vs_st_patch,''''facecolor'''',[.85 .85 .85],''''edgecolor'''',[1 1 1]);,'...
     'plot_CC_A_vs_st_line = [''''plot('''',char(Selected_Graph_String_2),''''.lags,'''',char(Selected_Graph_String_2),''''.cov,''''''''k'''''''',''''''''LineWidth'''''''',2)'''']; eval(plot_CC_A_vs_st_line); end''])']);                                                                                                

                


%      'plot_PSTH = [''''bar('''',char(Selected_Graph_String_2),''''.x,'''',char(Selected_Graph_String_2),''''.y,''''''''k'''''''')''''];eval(plot_PSTH);,'...
%      'y_lim = get(gca,''''ylim'''')'']);']);

%%%%%%%%%%%%%%%%%%%%%%%%

% Filter_menu = uimenu(Analysis_menu,'Label','Filter','CallBack',...
%     ['load sp_filt_300_5000; Temp_filename_raw(:,1:end-1) = filtfilt(filt_300_5000.tf.num,filt_300_5000.tf.den,Temp_filename_raw(:,1:end-1));,'...
%      'cla; plot(Temp_filename_raw(:,end),Temp_filename_raw(:,1:end-1),''k''); ylabel(''mV''); xlabel(''ms''); axis auto;,'...
%      'Trace_no_listbox = uicontrol(gcf,''Style'',''listbox'',''Max'',2,''Position'', [1160 200 70 400],''String'',Trace_nos_cell,''BackgroundColor'',[1 1 1],''CallBack'','...
%      '[''Selected_Trace_no = get(gco,''''Value'''');,'...
%      'plot(Temp_filename_raw(:,end),Temp_filename_raw(:,Selected_Trace_no),''''k'''');,' ...
%      'if strcmp(get(Lock_Axes_menu,''''Checked''''),''''on'''') ==1, axis([x_lim_lock(1) x_lim_lock(2) y_lim_lock(1) y_lim_locK(2)]), end;',...
%      'zoom; Selected_Trace_no_str = num2str(Selected_Trace_no); legend(Selected_Trace_no_str);'']);,']);
% %set(gca,''''EdgeColor'''',[0 0 0]);
% %     'PSTH_userinpt_cellchar1_conv = char(PSTH_userinpt(1));,'...
% %      'PSTH_userinpt_charnum1_conv = str2num(PSTH_userinpt_cellchar1_conv);,'...
%      'No_bins = (length(Temp_filename_raw)/10)/PSTH_userinpt_charnum1_conv;'...
%      'PSTH_str1 = [''PSTH_'',PSTH_userinpt_cellchar1_conv,'' = hist(Temp_array_for_spiketimes,No_bins);''];'...
%      'eval(PSTH_str1); PSTH_str2 = [''PSTH_'',PSTH_userinpt_cellchar1_conv]; cla; bar(eval(PSTH_str2)); Graph_strings{1} = PSTH_str1(1:6);'...
%      'if length(Graph_strings) >= 1,',...
%      'Graph_strings{length(Graph_strings)+1} = PSTH_str1(1:6); end']);

