warning off MATLAB:break_outside_of_loop

FindSpikes1_parameters = {'Minimal Amplitude (mV)','Maximal Amplitude (mV)','Minimal Event Width (ms)','Maximal Event Width (ms)'};
FindSpikes2_parameters = {'Spike Direction (Enter +1 for positive-going peaks and -1 for negative-going peaks','Minimal Amplitude (mV)','Maximal Amplitude (mV)','Minimal Event Width (ms)','Maximal Event Width (ms)'};
FindSpikes_dialogbox_title = 'Spike Discrimination Parameters';
FindSpikes_button_exe = uicontrol(gcf,'Style','pushbutton','Position',[10 510 100 25],...
    'String','Find Spikes','CallBack',...
    ['if exist(''Temp_filename_raw'') == 0, warndlg(''No traces loaded. Traces must be loaded before spikes can be discriminated.'',''Find Spikes'');',...
     'return, end;',...
     'FindSpikes_Type_userinpt = {''Findspikes I'',''Findspikes II''};,'...
     '[FindSpikes_Type_sel, OK] = listdlg(''PromptString'', ''Select Method:'','...
     '''SelectionMode'', ''single'',''ListString'',FindSpikes_Type_userinpt,''ListSize'',[150 100]);,'...
     'if FindSpikes_Type_sel == 1,'...  
     'FindSpikes_userinpt = inputdlg(FindSpikes1_parameters,FindSpikes_dialogbox_title);'...
     'temp_spike_times = findspikes_win_SE(Temp_filename_raw(:,1:end-1),str2num(char(LoadTraces_userinpt(4))),'...
     '{str2num(char(FindSpikes_userinpt(1))) str2num(char(FindSpikes_userinpt(2))) str2num(char(FindSpikes_userinpt(3))) str2num(char(FindSpikes_userinpt(4)))},0);,'...
     'hold on; for i = 1:size(Temp_filename_raw,2)-1,'...
     'plot(Temp_filename_raw(:,end),Temp_filename_raw(:,i),''k''); ,'...
     'plot(eval([''spike_times_trace_'',num2str(i)]),eval([''spike_peaks_trace_'',num2str(i)]),''ro''); end; x_lim = get(gca,''xlim''); y_lim = get(gca,''ylim'');,'...
     'plot([1 max(Temp_filename_raw(:,end))],[str2num(char(FindSpikes_userinpt(1))) str2num(char(FindSpikes_userinpt(1)))],''r''),'...
     'plot([1 max(Temp_filename_raw(:,end))],[str2num(char(FindSpikes_userinpt(2))) str2num(char(FindSpikes_userinpt(2)))],''r''),'...
     'axis auto,'...
     'uicontrol(gcf,''Style'',''text'',''Position'',[10 205 100 25],''String'',''Events found:'',''BackgroundColor'',[.8 .8 .8],''FontWeight'',''bold'');,'...
     'uicontrol(gcf,''Style'',''frame'',''Position'',[10 185 100 25],''BackgroundColor'',[1 1 1]);,'...
     'uicontrol(gcf,''Style'',''text'',''Position'',[15 194 90 10],''String'',size(cat(2,temp_spike_times{:}),2),''BackgroundColor'',[1 1 1]);,'...
     'uicontrol(gcf,''Style'',''text'',''Position'',[890 230 300 420],''String'',[''Trace Type          Trace Number          Channel Number''],''FontWeight'',''bold'',''BackgroundColor'',[.8 .8 .8]);'...
     'parse_FindSpikes; Psk_listbox = uicontrol(gcf,''Style'',''listbox'',''Position'', [900 235 300 400],''String'',Spike_Trace_nos_cell,''BackgroundColor'',[1 1 1],''CallBack'','...
     '[''Selected_psk = get(gco,''''Value'''');,'...
     'cla; hold on; plot(Temp_filename_raw(:,end), Temp_filename_raw(:,Selected_psk),''''k'''');,'...
     'plot(eval([''''spike_times_trace_'''',num2str(Selected_psk)]),eval([''''spike_peaks_trace_'''',num2str(Selected_psk)]),''''ro'''');,'... 
     'ylabel(''''mV''''); xlabel(''''ms'''');,'...
     'plot([1 max(Temp_filename_raw(:,end))],[str2num(char(FindSpikes_userinpt(1))) str2num(char(FindSpikes_userinpt(1)))],''''r'''');,'...
     'plot([1 max(Temp_filename_raw(:,end))],[str2num(char(FindSpikes_userinpt(2))) str2num(char(FindSpikes_userinpt(2)))],''''r'''');,'...
     'if strcmp(get(Lock_Axes_menu,''''Checked''''),''''on'''') == 1, axis([x_lim_lock(1) x_lim_lock(2) y_lim_lock(1) y_lim_lock(2)]), else,',...
     'axis auto; end; zoom on'']); zoom on;,'...
     'elseif FindSpikes_Type_sel == 2,'... 
     'FindSpikes_userinpt = inputdlg(FindSpikes2_parameters,FindSpikes_dialogbox_title);,'...
     'temp_spike_times = findspikes_win2_SE(Temp_filename_raw(:,1:end-1),str2num(char(LoadTraces_userinpt(4))),'...
     '[str2num(char(FindSpikes_userinpt(2))) str2num(char(FindSpikes_userinpt(3)))],str2num(char(FindSpikes_userinpt(1))),[str2num(char(FindSpikes_userinpt(4))) str2num(char(FindSpikes_userinpt(5)))],''xxxx'');,'...
     'temp_spike_peaks = temp_spike_times(:,2); temp_spike_times(:,2) = [];,'...    
     'hold on; for i = 1:size(Temp_filename_raw,2)-1,'...
     'plot(Temp_filename_raw(:,end),Temp_filename_raw(:,i),''k''); plot(temp_spike_times{i,1},temp_spike_peaks{i,1},''ro'');,'...
     'plot([1 max(Temp_filename_raw(:,end))],[str2num(char(FindSpikes_userinpt(2))) str2num(char(FindSpikes_userinpt(2)))],''r''),'...
     'plot([1 max(Temp_filename_raw(:,end))],[str2num(char(FindSpikes_userinpt(3))) str2num(char(FindSpikes_userinpt(3)))],''r''),'...
     'axis auto; end;,'...
     'uicontrol(gcf,''Style'',''text'',''Position'',[10 205 100 25],''String'',''Events found:'',''BackgroundColor'',[.8 .8 .8],''FontWeight'',''bold'');,'...
     'uicontrol(gcf,''Style'',''frame'',''Position'',[10 185 100 25],''BackgroundColor'',[1 1 1]);,'...
     'uicontrol(gcf,''Style'',''text'',''Position'',[15 194 90 10],''String'',size(cat(2,temp_spike_times{:}),2),''BackgroundColor'',[1 1 1]);,'...
     'uicontrol(gcf,''Style'',''text'',''Position'',[890 230 300 420],''String'',[''Trace Type          Trace Number          Channel Number''],''FontWeight'',''bold'',''BackgroundColor'',[.8 .8 .8]);'...
     'Psk_listbox = uicontrol(gcf,''Style'',''listbox'',''Position'', [900 235 300 400],''String'',Trace_nos_cell,''BackgroundColor'',[1 1 1],''CallBack'','...
     '[''Selected_psk = get(gco,''''Value'''');,'...
     'cla; hold on; plot(Temp_filename_raw(:,end), Temp_filename_raw(:,Selected_psk),''''k'''');,'...
     'plot(temp_spike_times{Selected_psk,1},temp_spike_peaks{Selected_psk,1},''''ro'''');,'... 
     'ylabel(''''mV''''); xlabel(''''ms'''');,'...
     'plot([1 max(Temp_filename_raw(:,end))],[str2num(char(FindSpikes_userinpt(2))) str2num(char(FindSpikes_userinpt(2)))],''''r'''');,'...
     'plot([1 max(Temp_filename_raw(:,end))],[str2num(char(FindSpikes_userinpt(3))) str2num(char(FindSpikes_userinpt(3)))],''''r'''');,'...
     'if strcmp(get(Lock_Axes_menu,''''Checked''''),''''on'''') == 1, axis([x_lim_lock(1) x_lim_lock(2) y_lim_lock(1) y_lim_lock(2)]), else,',...
     'axis auto; end; zoom on'']); zoom on; end;,']);
    

%findspikes_win2_SE(traces, Fs, [min_amp max_amp], direction, [min_time max_time], 'plot')



%     ['if exist(''Temp_filename_raw'') == 0, warndlg(''No traces loaded. Traces must be loaded before spikes can be discriminated.'',''Find Spikes'');',...
%      'break, end, FindSpikes_userinpt = inputdlg(FindSpikes_parameters,FindSpikes_dialogbox_title);'...
%      'FindSpikes_userinpt_cellchar1_conv = char(FindSpikes_userinpt(1));,'...
%      'FindSpikes_userinpt_cellchar2_conv = char(FindSpikes_userinpt(2));,'...
%      'FindSpikes_userinpt_cellchar3_conv = char(FindSpikes_userinpt(3));,'...
%      'FindSpikes_userinpt_cellchar4_conv = char(FindSpikes_userinpt(4));,'...
%      'FindSpikes_userinpt_cellchar5_conv = char(FindSpikes_userinpt(5));,'...
%      'FindSpikes_userinpt_charnum1_conv = str2num(FindSpikes_userinpt_cellchar1_conv);,'...
%      'FindSpikes_userinpt_charnum2_conv = str2num(FindSpikes_userinpt_cellchar2_conv);,'...
%      'FindSpikes_userinpt_charnum3_conv = str2num(FindSpikes_userinpt_cellchar3_conv);,'...
%      'FindSpikes_userinpt_charnum4_conv = str2num(FindSpikes_userinpt_cellchar4_conv);,'...
%      'FindSpikes_userinpt_charnum5_conv = str2num(FindSpikes_userinpt_cellchar5_conv);,'...
%      'findspikes_win_SE(Temp_filename_raw(:,1:end-1),str2num(char(LoadTraces_userinpt(4))),'...
%      'FindSpikes_userinpt_charnum1_conv,FindSpikes_userinpt_charnum2_conv,FindSpikes_userinpt_charnum3_conv,'...
%      'FindSpikes_userinpt_charnum4_conv,0);,'...
%      'hold on; for i = 1:size(Temp_filename_raw,2)-1,'...
%      'plot(Temp_filename_raw(:,end),Temp_filename_raw(:,i),''k''); ,'...
%      'plot(eval([''spike_times_trace_'',num2str(i)]),eval([''spike_peaks_trace_'',num2str(i)]),''ro''); end; x_lim = get(gca,''xlim''); y_lim = get(gca,''ylim'');,'...
%      'plot([1 max(Temp_filename_raw(:,end))],[str2num(char(FindSpikes_userinpt(1))) str2num(char(FindSpikes_userinpt(1)))],''r''),'...
%      'plot([1 max(Temp_filename_raw(:,end))],[str2num(char(FindSpikes_userinpt(2))) str2num(char(FindSpikes_userinpt(2)))],''r''),'...
%      'axis auto,'...
%      'uicontrol(gcf,''Style'',''text'',''Position'',[10 245 100 25],''String'',''Events found:'',''BackgroundColor'',[.8 .8 .8],''FontWeight'',''bold'');,'...
%      'uicontrol(gcf,''Style'',''frame'',''Position'',[10 225 100 25],''BackgroundColor'',[1 1 1]);,'...
%      'uicontrol(gcf,''Style'',''text'',''Position'',[15 234 90 10],''String'',length(SPIKES),''BackgroundColor'',[1 1 1]);,'...
%      'uicontrol(gcf,''Style'',''text'',''Position'',[1147 200 90 420],''String'',''Trace (s):'',''FontWeight'',''bold'',''BackgroundColor'',[.8 .8 .8]);'...
%      'Psk_listbox = uicontrol(gcf,''Style'',''listbox'',''Position'', [1160 200 70 400],''String'',Trace_nos_cell,''BackgroundColor'',[1 1 1],''CallBack'','...
%      '[''Selected_psk = get(gco,''''Value'''');,'...
%      'cla; hold on; plot(Temp_filename_raw(:,end), Temp_filename_raw(:,Selected_psk),''''k'''');,'...
%      'plot(eval([''''spike_times_trace_'''',num2str(Selected_psk)]),eval([''''spike_peaks_trace_'''',num2str(Selected_psk)]),''''ro'''');,'... 
%      'ylabel(''''mV''''); xlabel(''''ms'''');,'...
%      'plot([1 max(Temp_filename_raw(:,end))],[str2num(char(FindSpikes_userinpt(1))) str2num(char(FindSpikes_userinpt(1)))],''''r'''');,'...
%      'plot([1 max(Temp_filename_raw(:,end))],[str2num(char(FindSpikes_userinpt(2))) str2num(char(FindSpikes_userinpt(2)))],''''r'''');,'...
%      'if strcmp(get(Lock_Axes_menu,''''Checked''''),''''on'''') == 1, axis([x_lim_lock(1) x_lim_lock(2) y_lim_lock(1) y_lim_lock(2)]), else,',...
%      'axis auto; end; zoom on'']); zoom on;']);

%'axis([0 max(Temp_filename_raw(:,end)) y_lim(1)+.2*y_lim(1) y_lim(2)+.2*y_lim(2)]),'...

 %'x_lim = get(gca,''''xlim''''); y_lim = get(gca,''''ylim''''); axis([0 max(Temp_filename_raw(:,end)) y_lim(1)+.2*y_lim(1) y_lim(2)+.2*y_lim(2)]); end; zoom on'']); zoom on;']);

%'axis([0 max(Temp_filename_raw(:,end)) str2num(char(FindSpikes_userinpt(1)))-20 max(max(Temp_filename_raw(:,1:end-1)))+20]),'...


% 'Trace_no_listbox = uicontrol(gcf,''Style'',''listbox'',''Position'', [1160 200 70 400],''String'',Trace_nos,''BackgroundColor'',[1 1 1],''CallBack'','...
%     '[''Selected_Trace_no = get(gco,''''Value'''');,'...
%     'plot(Temp_filename_raw(:,end),Temp_filename_raw(:,Selected_Trace_no),''''k'''');,' ...
%     'zoom; Selected_Trace_no_str = num2str(Selected_Trace_no); legend(Selected_Trace_no_str);'']);']);


     %'plot(eval([''''spike_times_trace_'''',num2str(Selected_psk)]),eval([''''spike_peaks_trace_'''',num2str(Selected_psk)]),''''''''ro'''''''');'']);']);
%'Plot_psk_str = [''''plot(Temp_filename_spiketimes_trace_'''',num2str(Selected_psk),'''',Temp_filename_peakval_trace_'''',num2str(Selected_psk),'''',''''''''ro'''''''')''''];,'...
%      'eval(Plot_psk_str); zoom on;'']);'])