% Setup Advanced plotting options

Advanced_plot_menu = uimenu(gcf,'Label','Advanced Plot','Position',1);



% Add channels
Add_channel_menu = uimenu(Advanced_plot_menu,'Label','Add channel(s)');

% Edit axes
Edit_Axes = uimenu(Advanced_plot_menu,'Label','Edit Axes','CallBack','axlimdlg');

% Lock/Unlock Axes
Lock_Axes_menu = uimenu(Advanced_plot_menu,'Label','Lock Axes','CallBack',...
    ['if strcmp(get(Lock_Axes_menu,''Checked''),''off'') == 1,',...
    'set(Lock_Axes_menu,''Checked'',''on''),',...
    'y_lim_lock = get(gca,''ylim''); x_lim_lock = get(gca,''xlim'');',...
    'elseif strcmp(get(Lock_Axes_menu,''Checked''),''on'') == 1,',...
    'set(Lock_Axes_menu,''Checked'',''off''); end']);

% Multiplot
Multiplot_menu = uimenu(Advanced_plot_menu,'Label','Multiplot');
Multiplot_submenu = uimenu(Multiplot_menu,'Label','Plot Selected Graphs','CallBack',...
    ['figure;,'...
     'multiplot_SE_str = [''multiplot_SE(2,0,0,Temp_filename_raw(:,end),1:size(Temp_filename_raw,1),Temp_filename_raw(:,1:end-1),['',num2str(Selected_Trace_no),''])''];,'...
     'eval(multiplot_SE_str)']);

Resize_menu_x_y_parameters = {'Graph','x min','x max','x tick','y min','y max','y tick'};
Resize_menu_x_y_dlg_title = 'Resize X and Y (single)';
Resize_menu_x_y = uimenu(Multiplot_menu,'Label','Resize X and Y (single)','CallBack',...
    ['resize_x_y_userinpt = inputdlg(Resize_menu_x_y_parameters,Resize_menu_x_y_dlg_title);,'...
     'resize_SE(2,str2num(char(resize_x_y_userinpt(1))),str2num(char(resize_x_y_userinpt(2))),str2num(char(resize_x_y_userinpt(3))),',...
     'str2num(char(resize_x_y_userinpt(4))),str2num(char(resize_x_y_userinpt(5))),str2num(char(resize_x_y_userinpt(6))),',...
     'str2num(char(resize_x_y_userinpt(7))))']);

Resize_menu_all_x_parameters = {'x min','x max','x tick'};
Resize_menu_all_x_dlg_title = 'Resize X (all)';
Resize_menu_all_x = uimenu(Multiplot_menu,'Label','Resize X (all)','CallBack',...
    ['resize_all_x_userinpt = inputdlg(Resize_menu_all_x_parameters,Resize_menu_all_x_dlg_title);,'...
     'resize_all_x_SE(2,str2num(char(resize_all_x_userinpt(1))),str2num(char(resize_all_x_userinpt(2))),str2num(char(resize_all_x_userinpt(3))))']);

Resize_menu_all_x_y_parameters = {'x min','x max','x tick','y min','y max','y tick'};
Resize_menu_all_x_y_dlg_title = 'Resize X and Y (all)';
Resize_menu_all_x_y = uimenu(Multiplot_menu,'Label','Resize X and Y (all)','CallBack',...
    ['resize_all_x_y_userinpt = inputdlg(Resize_menu_all_x_y_parameters,Resize_menu_all_x_y_dlg_title);,'...
     'resize_all_SE(2,str2num(char(resize_all_x_y_userinpt(1))),str2num(char(resize_all_x_y_userinpt(2))),str2num(char(resize_all_x_y_userinpt(3))),',...
     'str2num(char(resize_all_x_y_userinpt(4))),str2num(char(resize_all_x_y_userinpt(5))),str2num(char(resize_all_x_y_userinpt(6))))']);

Autoscale_all_multiplot_SE_menu = uimenu(Multiplot_menu,'Label','Autoscale (all)','CallBack','autoscale_all_multiplot_SE');




