% Initialize Graph_str_cell = {};
Graph_str_cell = {};

%NOTE: Put in the multiple graph for loop in the 2x2 graphs; also put separate_color_traces and legend!!!!

GenerateGraphs_parameters = {'How many rows?','How many columns?'};
GenerateGraphs_dialogbox_title = 'Generate Graphs';
GenerateGraphs_button_exe = uicontrol(gcf,'Style','pushbutton','Position',[10 460 100 25],...
    'String','Generate Graphs','CallBack',...
    ['Graph_strings = [Trace_str_cell Graph_str_cell]; GenerateGraphs_Type_userinpt = {''1x1'',''2x2''};,'...
    '[GenerateGraphs_Type_sel, OK] = listdlg(''PromptString'', ''Select Graph Type:'','...
    '''SelectionMode'', ''single'',''ListString'',GenerateGraphs_Type_userinpt,''ListSize'',[150 100]);,'...
    'if GenerateGraphs_Type_sel == 1,'...     
    'figure; set(gcf,''Position'',[5 35 1272 715]);subplot(1,1,1),'... 
    'GenerateGraphs_subbutton_1_1 = uicontrol(gcf,''Style'',''pushbutton'',''Position'',[950 30 100 20],'...
    '''String'',''Select Graph'',''CallBack'',[''GenerateGraphs_subbutton_1_1_lstdlg = listdlg(''''PromptString'''',''''Select a Graph'''',''''SelectionMode'''',''''multiple'''',''''ListString'''',Graph_strings);,'...
    'if size(Trace_str_cell,2) >= GenerateGraphs_subbutton_1_1_lstdlg >= 1,'...
    'for i = 1:size(GenerateGraphs_subbutton_1_1_lstdlg,2), plot(eval(char(Graph_strings(GenerateGraphs_subbutton_1_1_lstdlg(i))))); hold on; end;,'...
    'elseif Graph_strings{GenerateGraphs_subbutton_1_1_lstdlg}(1:3) == ''''ISI'''','...
    'cla; plot_ISI = [''''bar('''',char(Graph_strings(GenerateGraphs_subbutton_1_1_lstdlg)),''''.hist_x,'''',char(Graph_strings(GenerateGraphs_subbutton_1_1_lstdlg)),''''.hist_y,''''''''k'''''''')''''];eval(plot_ISI);,'...
    'axis_ISI = [''''axis([0 300 0 max('''',char(Graph_strings(GenerateGraphs_subbutton_1_1_lstdlg)),''''.hist_y)+10])'''']; eval(axis_ISI),'...
    'y_lim = get(gca,''''ylim'''');,'...
    'mean_str = [''''text(200,.80*y_lim(2),[''''''''mean = '''''''',num2str(eval([char(Graph_strings(GenerateGraphs_subbutton_1_1_lstdlg)),''''''''.mean''''''''])),'''''''' ms''''''''])''''];eval(mean_str);,'...
    'mode_str = [''''text(200,.75*y_lim(2),[''''''''mode = '''''''',num2str(eval([char(Graph_strings(GenerateGraphs_subbutton_1_1_lstdlg)),''''''''.mode''''''''])),'''''''' ms''''''''])''''];eval(mode_str);,'...
    'median_str = [''''text(200,.70*y_lim(2),[''''''''median = '''''''',num2str(eval([char(Graph_strings(GenerateGraphs_subbutton_1_1_lstdlg)),''''''''.median''''''''])),''''''''ms''''''''])''''];eval(median_str);,'...
    'std_str = [''''text(200,.65*y_lim(2),[''''''''std = '''''''',num2str(eval([char(Graph_strings(GenerateGraphs_subbutton_1_1_lstdlg)),''''''''.std''''''''])),'''''''' ms''''''''])''''];eval(std_str);,'...
    'cv_str = [''''text(200,.60*y_lim(2),[''''''''cv = '''''''',num2str(eval([char(Graph_strings(GenerateGraphs_subbutton_1_1_lstdlg)),''''''''.cv''''''''])),''''''''d''''''''])''''];eval(cv_str);,'...
    'frequency_str = [''''text(200,.55*y_lim(2),[''''''''frequency = '''''''',num2str(eval([char(Graph_strings(GenerateGraphs_subbutton_1_1_lstdlg)),''''''''.freq''''''''])),'''''''' Hz''''''''])''''];eval(frequency_str);,'...
    'elseif Graph_strings{GenerateGraphs_subbutton_1_1_lstdlg}(1:4) == ''''PSTH'''','...
    'cla; axis auto; hold on; plot_PSTH = [''''bar('''',char(Graph_strings(GenerateGraphs_subbutton_1_1_lstdlg)),''''.x,'''',char(Graph_strings(GenerateGraphs_subbutton_1_1_lstdlg)),''''.y,''''''''k'''''''')''''];eval(plot_PSTH);'...
    'for i = 1:size(temp_spike_times,1), raster_plot_str = [''''plot(temp_spike_times{i,1},i+10+max(eval([char(Graph_strings(GenerateGraphs_subbutton_1_1_lstdlg)),''''''''.y''''''''])),''''''''ko'''''''',''''''''MarkerSize'''''''',1); hold on''''];eval(raster_plot_str); end;,'...
    'set(gca,''''ylim'''',[0 size(temp_spike_times,1)+11+max(eval([char(Graph_strings(GenerateGraphs_subbutton_1_1_lstdlg)),''''.y'''']))]);,'...
    'plot_PSTH_bar = [''''plot(['''',char(Graph_strings(GenerateGraphs_subbutton_1_1_lstdlg)),''''.trigger '''' char(Graph_strings(GenerateGraphs_subbutton_1_1_lstdlg)),''''.trigger],[0 size(temp_spike_times,1)+11+max(eval([char(Graph_strings(GenerateGraphs_subbutton_1_1_lstdlg)),''''''''.y'''''''']))],''''''''k'''''''')''''];eval(plot_PSTH_bar);'...
    'elseif Graph_strings{GenerateGraphs_subbutton_1_1_lstdlg}(1:5) == ''''Tr_Av'''','...
    'cla; axis auto; plot_Tr_Av_str = [''''plot('''',char(Graph_strings(GenerateGraphs_subbutton_1_1_lstdlg)),''''(:,2),'''',char(Graph_strings(GenerateGraphs_subbutton_1_1_lstdlg)),''''(:,1),''''''''k'''''''')''''];eval(plot_Tr_Av_str); ylabel(''''uV''''); xlabel(''''ms'''');,'... 
    'elseif Graph_strings{GenerateGraphs_subbutton_1_1_lstdlg}(1:3) == ''''STA'''','...
    'cla; axis auto; plot_STA_patch = [''''STA_patch = patch('''',char(Graph_strings{GenerateGraphs_subbutton_1_1_lstdlg}),''''.CI_bar_x,'''',char(Graph_strings{GenerateGraphs_subbutton_1_1_lstdlg}),''''.CI_bar_y,''''''''w'''''''')'''']; eval(plot_STA_patch);,'...
    'plot_STA_line = [''''plot('''',char(Graph_strings{GenerateGraphs_subbutton_1_1_lstdlg}),''''.sta_x,'''',char(Graph_strings{GenerateGraphs_subbutton_1_1_lstdlg}),''''.sta_y,''''''''k'''''''')'''']; eval(plot_STA_line);,'...
    'set(STA_patch,''''facecolor'''',[.85 .85 .85],''''edgecolor'''',[1 1 1]);,'...
    'elseif Graph_strings{GenerateGraphs_subbutton_1_1_lstdlg}(1:12) == ''''AC_st_vs_st_'''','...
    'cla; axis auto; plot_AC_st_vs_st_patch = [''''AC_st_vs_st_patch = patch('''',char(Graph_strings{GenerateGraphs_subbutton_1_1_lstdlg}),''''.CI_bar_x,'''',char(Graph_strings{GenerateGraphs_subbutton_1_1_lstdlg}),''''.CI_bar_y,''''''''w'''''''')'''']; eval(plot_AC_st_vs_st_patch);,'...   
    'set(AC_st_vs_st_patch,''''facecolor'''',[.85 .85 .85],''''edgecolor'''',[1 1 1]);,'...
    'plot_AC_st_vs_st_line = [''''plot('''',char(Graph_strings{GenerateGraphs_subbutton_1_1_lstdlg}),''''.lags,'''',char(Graph_strings{GenerateGraphs_subbutton_1_1_lstdlg}),''''.cov,''''''''k'''''''',''''''''LineWidth'''''''',2)'''']; eval(plot_AC_st_vs_st_line);,'...                                                                                                
    'elseif Graph_strings{GenerateGraphs_subbutton_1_1_lstdlg}(1:10) == ''''AC_A_vs_A_'''','...
    'cla; axis auto; plot_AC_A_vs_A_patch = [''''AC_A_vs_A_patch = patch('''',char(Graph_strings{GenerateGraphs_subbutton_1_1_lstdlg}),''''.CI_bar_x,'''',char(Graph_strings{GenerateGraphs_subbutton_1_1_lstdlg}),''''.CI_bar_y,''''''''w'''''''')'''']; eval(plot_AC_A_vs_A_patch);,'...   
    'set(AC_A_vs_A_patch,''''facecolor'''',[.85 .85 .85],''''edgecolor'''',[1 1 1]);,'...
    'plot_AC_A_vs_A_line = [''''plot('''',char(Graph_strings{GenerateGraphs_subbutton_1_1_lstdlg}),''''.lags,'''',char(Graph_strings{GenerateGraphs_subbutton_1_1_lstdlg}),''''.cov,''''''''k'''''''',''''''''LineWidth'''''''',2)'''']; eval(plot_AC_A_vs_A_line);,'...                                                                                                
    'elseif Graph_strings{GenerateGraphs_subbutton_1_1_lstdlg}(1:10) == ''''CC_A_vs_A_'''','...
    'cla; axis auto; plot_CC_A_vs_A_patch = [''''CC_A_vs_A_patch = patch('''',char(Graph_strings{GenerateGraphs_subbutton_1_1_lstdlg}),''''.CI_bar_x,'''',char(Graph_strings{GenerateGraphs_subbutton_1_1_lstdlg}),''''.CI_bar_y,''''''''w'''''''')'''']; eval(plot_CC_A_vs_A_patch);,'...   
    'set(CC_A_vs_A_patch,''''facecolor'''',[.85 .85 .85],''''edgecolor'''',[1 1 1]);,'...
    'plot_CC_A_vs_A_line = [''''plot('''',char(Graph_strings{GenerateGraphs_subbutton_1_1_lstdlg}),''''.lags,'''',char(Graph_strings{GenerateGraphs_subbutton_1_1_lstdlg}),''''.cov,''''''''k'''''''',''''''''LineWidth'''''''',2)'''']; eval(plot_CC_A_vs_A_line); end'']);,'...                                                                                                 
    'GenerateGraphs_subbutton_1_2 = uicontrol(gcf,''Style'',''popupmenu'',''Position'',[1060 30 100 20],''String'',''Edit Graph|Autoscale|Clear|Label X Axis|Label Y Axis|Legend|Range|Separate Graphs|Title'',''CallBack'',[''GenerateGraphs_subbutton_1_2_value = get(GenerateGraphs_subbutton_1_2,''''Value'''');,'...
    'switch GenerateGraphs_subbutton_1_2_value,'...
    'case {1},'...
    'case {2},'...
    'axis auto,'...
    'case {3},'...
    'cla,'...
    'case {4},'... 
    'XLabel = inputdlg(''''Enter label for X axis'''',''''Label X axis''''); xlabel(XLabel);,'...
    'case {5},'...
    'YLabel = inputdlg(''''Enter label for Y axis'''',''''Label Y axis''''); ylabel(YLabel);,'...
    'case {6},'...
    'for i = 1:size(GenerateGraphs_subbutton_1_1_lstdlg,2), legend_parameters{1,i} = [''''Trace '''',num2str((GenerateGraphs_subbutton_1_1_lstdlg(i)))]; end;,'...
    'legend_dialogbox_title = ''''Enter Legend''''; legend_userinpt = inputdlg(legend_parameters,legend_dialogbox_title); legend(legend_userinpt);,'...
    'case {7},'...
    'axlimdlg,'...
    'case {8},'...
    'cla; separate_color_traces(GenerateGraphs_subbutton_1_1_lstdlg);',...
    'case {9},'...
    'Title = inputdlg(''''Enter Title for graph'''',''''Graph Title''''); title(Title);,'...    
    'end; '']);,'...
    'elseif GenerateGraphs_Type_sel == 2,'...
    'figure; set(gcf,''Position'',[5 35 1272 715]); for i = 1:4, subplot(2,2,i), end;,'...
    'GenerateGraphs_subbutton_1_1 = uicontrol(gcf,''Style'',''pushbutton'',''Position'',[375 350 100 20],'...
    '''String'',''Select Graph'',''CallBack'',[''GenerateGraphs_subbutton_1_1_lstdlg = listdlg(''''PromptString'''',''''Select a Graph'''',''''SelectionMode'''',''''single'''',''''ListString'''',Graph_strings); subplot(2,2,1); plot(eval(char(Graph_strings(GenerateGraphs_subbutton_1_1_lstdlg))))'']);,'...
    'GenerateGraphs_subbutton_1_2 = uicontrol(gcf,''Style'',''popupmenu'',''Position'',[485 350 100 20],''String'',''Autoscale|Clear|Label X Axis|Label Y Axis|Legend|Range|Title'',''CallBack'',[''GenerateGraphs_subbutton_1_2_value = get(GenerateGraphs_subbutton_1_2,''''Value'''');,'...
    'switch GenerateGraphs_subbutton_1_2_value,'...
    'case {1},'...
    'subplot(2,2,1); axis auto,'...
    'case {2},'...
    'subplot(2,2,1); cla,'...
    'case {3},'... 
    'XLabel = inputdlg(''''Enter label for X axis'''',''''Label X axis''''); subplot(2,2,1); xlabel(XLabel);,'...
    'case {4},'...
    'YLabel = inputdlg(''''Enter label for Y axis'''',''''Label Y axis''''); subplot(2,2,1); ylabel(YLabel);,'...
    'case {5},'...
    'case {6},'...
    'subplot(2,2,1); axlimdlg,'...
    'case {7},'...
    'Title = inputdlg(''''Enter Title for graph'''',''''Graph Title''''); subplot(2,2,1); title(Title);,'...    
    'end; '']);,'...    
    'GenerateGraphs_subbutton_2_1 = uicontrol(gcf,''Style'',''pushbutton'',''Position'',[950 350 100 20],'...
    '''String'',''Select Graph'',''CallBack'',[''GenerateGraphs_subbutton_2_1_lstdlg = listdlg(''''PromptString'''',''''Select a Graph'''',''''SelectionMode'''',''''single'''',''''ListString'''',Graph_strings); subplot(2,2,2); plot(eval(char(Graph_strings(GenerateGraphs_subbutton_2_1_lstdlg))))'']);,'...
    'GenerateGraphs_subbutton_2_2 = uicontrol(gcf,''Style'',''popupmenu'',''Position'',[1060 350 100 20],''String'',''Autoscale|Clear|Label X Axis|Label Y Axis|Legend|Range|Title'',''CallBack'',[''GenerateGraphs_subbutton_2_2_value = get(GenerateGraphs_subbutton_2_2,''''Value'''');,'...
    'switch GenerateGraphs_subbutton_2_2_value,'...
    'case {1},'...
    'subplot(2,2,2); axis auto,'...
    'case {2},'...
    'subplot(2,2,2); cla,'...
    'case {3},'... 
    'XLabel = inputdlg(''''Enter label for X axis'''',''''Label X axis''''); subplot(2,2,2); xlabel(XLabel);,'...
    'case {4},'...
    'YLabel = inputdlg(''''Enter label for Y axis'''',''''Label Y axis''''); subplot(2,2,2); ylabel(YLabel);,'...
    'case {5},'...
    'case {6},'...
    'subplot(2,2,2); axlimdlg,'...
    'case {7},'...
    'Title = inputdlg(''''Enter Title for graph'''',''''Graph Title''''); subplot(2,2,2); title(Title);,'...    
    'end; '']);,'...
    'GenerateGraphs_subbutton_3_1 = uicontrol(gcf,''Style'',''pushbutton'',''Position'',[375 30 100 20],'...
    '''String'',''Select Graph'',''CallBack'',[''GenerateGraphs_subbutton_3_1_lstdlg = listdlg(''''PromptString'''',''''Select a Graph'''',''''SelectionMode'''',''''single'''',''''ListString'''',Graph_strings); subplot(2,2,3); plot(eval(char(Graph_strings(GenerateGraphs_subbutton_3_1_lstdlg))))'']);,'...
    'GenerateGraphs_subbutton_3_2 = uicontrol(gcf,''Style'',''popupmenu'',''Position'',[485 30 100 20],''String'',''Autoscale|Clear|Label X Axis|Label Y Axis|Legend|Range|Title'',''CallBack'',[''GenerateGraphs_subbutton_3_2_value = get(GenerateGraphs_subbutton_3_2,''''Value'''');,'...
    'switch GenerateGraphs_subbutton_3_2_value,'...
    'case {1},'...
    'subplot(2,2,3); axis auto,'...
    'case {2},'...
    'subplot(2,2,3); cla,'...
    'case {3},'... 
    'XLabel = inputdlg(''''Enter label for X axis'''',''''Label X axis''''); subplot(2,2,3); xlabel(XLabel);,'...
    'case {4},'...
    'YLabel = inputdlg(''''Enter label for Y axis'''',''''Label Y axis''''); subplot(2,2,3); ylabel(YLabel);,'...
    'case {5},'...
    'case {6},'...
    'subplot(2,2,3); axlimdlg,'...
    'case {7},'...
    'Title = inputdlg(''''Enter Title for graph'''',''''Graph Title''''); subplot(2,2,3); title(Title);,'...    
    'end; '']);,'...
    'GenerateGraphs_subbutton_4_1 = uicontrol(gcf,''Style'',''pushbutton'',''Position'',[950 30 100 20],'...
    '''String'',''Select Graph'',''CallBack'',[''GenerateGraphs_subbutton_4_1_lstdlg = listdlg(''''PromptString'''',''''Select a Graph'''',''''SelectionMode'''',''''single'''',''''ListString'''',Graph_strings); subplot(2,2,4); plot(eval(char(Graph_strings(GenerateGraphs_subbutton_4_1_lstdlg))))'']);,'...
    'GenerateGraphs_subbutton_4_2 = uicontrol(gcf,''Style'',''popupmenu'',''Position'',[1060 30 100 20],''String'',''Autoscale|Clear|Label X Axis|Label Y Axis|Legend|Range|Title'',''CallBack'',[''GenerateGraphs_subbutton_4_2_value = get(GenerateGraphs_subbutton_4_2,''''Value'''');,'...
    'switch GenerateGraphs_subbutton_4_2_value,'...
    'case {1},'...
    'subplot(2,2,4); axis auto,'...
    'case {2},'...
    'subplot(2,2,4); cla,'...
    'case {3},'... 
    'XLabel = inputdlg(''''Enter label for X axis'''',''''Label X axis''''); subplot(2,2,4); xlabel(XLabel);,'...
    'case {4},'...
    'YLabel = inputdlg(''''Enter label for Y axis'''',''''Label Y axis''''); subplot(2,2,4); ylabel(YLabel);,'...
    'case {5},'...
    'case {6},'...
    'subplot(2,2,4); axlimdlg,'...
    'case {7},'...
    'Title = inputdlg(''''Enter Title for graph'''',''''Graph Title''''); subplot(2,2,4); title(Title);,'...    
    'end; '']); end']);
%end''])']);

% 'GenerateGraphs_userinpt = inputdlg(GenerateGraphs_parameters,GenerateGraphs_dialogbox_title);'...
%     'GenerateGraphs_userinpt_cellchar1_conv = char(GenerateGraphs_userinpt(1));,'...
%     'GenerateGraphs_userinpt_cellchar2_conv = char(GenerateGraphs_userinpt(2));,'...
%     'GenerateGraphs_userinpt_charnum1_conv = str2num(GenerateGraphs_userinpt_cellchar1_conv);,'...
%     'GenerateGraphs_userinpt_charnum2_conv = str2num(GenerateGraphs_userinpt_cellchar2_conv);,'...
%     'GenerateGraphs_coordinates = [GenerateGraphs_userinpt_charnum1_conv, GenerateGraphs_userinpt_charnum2_conv];,'... 
%     'GenerateGraphs_coordinates_str = num2str(GenerateGraphs_coordinates);'...
%     'switch GenerateGraphs_coordinates_str,'...
%     'case {''1  1''},'...


% 'elseif Graph_strings{GenerateGraphs_subbutton_1_1_lstdlg}(1:3) == ''''isi'''';,'...
%     'plot_ISI = [''''bar('''',char(Graph_strings(GenerateGraphs_subbutton_1_1_lstdlg)),''''.hist_x,'''',char(Graph_strings(GenerateGraphs_subbutton_1_1_lstdlg)),''''.hist_y,''''''''b'''''''')''''];eval(plot_ISI);,'...
%     'axis_ISI = [''''axis([0 300 0 max('''',char(Graph_strings(GenerateGraphs_subbutton_1_1_lstdlg)),''''.hist_y)+10])'''']; eval(axis_ISI),'...
%     'y_lim = get(gca,''''ylim'''');,'...
%     'mean_str = [''''text(200,.80*y_lim(2),[''''''''mean = '''''''',num2str(eval([char(Graph_strings(GenerateGraphs_subbutton_1_1_lstdlg)),''''''''.mean''''''''])),'''''''' ms''''''''])''''];eval(mean_str);,'...
%     'mode_str = [''''text(200,.75*y_lim(2),[''''''''mode = '''''''',num2str(eval([char(Graph_strings(GenerateGraphs_subbutton_1_1_lstdlg)),''''''''.mode''''''''])),'''''''' ms''''''''])''''];eval(mode_str);,'...
%     'median_str = [''''text(200,.70*y_lim(2),[''''''''median = '''''''',num2str(eval([char(Graph_strings(GenerateGraphs_subbutton_1_1_lstdlg)),''''''''.median''''''''])),''''''''ms''''''''])''''];eval(median_str);,'...
%     'std_str = [''''text(200,.65*y_lim(2),[''''''''std = '''''''',num2str(eval([char(Graph_strings(GenerateGraphs_subbutton_1_1_lstdlg)),''''''''.std''''''''])),'''''''' ms''''''''])''''];eval(std_str);,'...
%     'cv_str = [''''text(200,.60*y_lim(2),[''''''''cv = '''''''',num2str(eval([char(Graph_strings(GenerateGraphs_subbutton_1_1_lstdlg)),''''''''.cv''''''''])),''''''''d''''''''])''''];eval(cv_str);,'...
%     'frequency_str = [''''text(200,.55*y_lim(2),[''''''''frequency = '''''''',num2str(eval([char(Graph_strings(GenerateGraphs_subbutton_1_1_listdlg)),''''''''.freq''''''''])),'''''''' Hz''''''''])''''];eval(frequency_str); end'']);,'...