function createfigure(freq, PDnormrest, PDnormactive, DYSrestM1Norm2, DYSactiveM1Norm2,...
    DYSrestSTNNorm2,DYSactiveSTNNorm2)
%CREATEFIGURE(X1,YMATRIX1,YMATRIX2,YMATRIX3,YMATRIX4)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  YMATRIX2:  matrix of y data
%  YMATRIX3:  matrix of y data
%  YMATRIX4:  matrix of y data

%  Auto-generated by MATLAB on 24-Apr-2009 18:24:38
X1 = freq;
% Create figure
figure1 = figure('Name','Characteristic PSD plots 2',...
    'Color',[1 1 1]);

% Create axes
axes('Parent',figure1,'Position',[0.1324 0.5275 0.3347 0.3412]);
box('on');
hold('all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,ETnormrest,'LineWidth',2);
set(plot1(2),'Color',[1 0 0]);

% Create ylabel
ylabel('Normalized mean PSD across all epochs (AU)','FontSize',8);

% Create title
title('M1','FontWeight','bold','FontSize',12);

% Create axes
axes('Parent',figure1,'Position',[0.5432 0.5254 0.3347 0.3412]);
box('on');
hold('all');


% Create multiple lines using matrix input to plot
plot2 = plot(X1,YMatrix2,'LineWidth',2);
set(plot2(2),'Color',[1 0 0]);

% Create title
title('STN','FontWeight','bold','FontSize',12);

% Create axes
axes('Parent',figure1,'Position',[0.1316 0.08887 0.3347 0.3412]);
box('on');
hold('all');

% Create multiple lines using matrix input to plot
plot3 = plot(X1,YMatrix3,'LineWidth',2);
set(plot3(2),'Color',[1 0 0]);

% Create xlabel
xlabel('Frequency (Hz)','FontSize',8);

% Create ylabel
ylabel('Normalized mean OSD across all epochs (AU)','FontSize',8);

% Create axes
axes1 = axes('Parent',figure1,'Position',[0.5424 0.08722 0.3347 0.3412]);
box('on');
hold('all');

% Create multiple lines using matrix input to plot
plot4 = plot(X1,YMatrix4,'LineWidth',2);
set(plot4(1),'DisplayName','Rest');
set(plot4(2),'DisplayName','Active','Color',[1 0 0]);

% Create xlabel
xlabel('Frequency (Hz)','FontSize',8);

% Create title
title({''});

% Create legend
% legend1 = legend(axes1,'show');
% set(legend1,'EdgeColor',[1 1 1],'YColor',[1 1 1],'XColor',[1 1 1],...
%     'Position',[0.7889 0.9135 0.07266 0.04789]);

% Create textbox
annotation(figure1,'textbox','String',{'PD'},'FontWeight','bold',...
    'FontSize',12,...
    'FitHeightToText','off',...
    'LineStyle','none',...
    'Position',[0.006993 0.7462 0.03896 0.04103]);

% Create textbox
annotation(figure1,'textbox','String',{'Dystonia'},'FontWeight','bold',...
    'FontSize',12,...
    'FitHeightToText','off',...
    'LineStyle','none',...
    'Position',[0.001998 0.2553 0.08092 0.03951]);

% Create textbox
annotation(figure1,'textbox','String',{'Characteristic PSD Plots'},...
    'HorizontalAlignment','center',...
    'FontWeight','demi',...
    'FontSize',14,...
    'FitHeightToText','off',...
    'LineStyle','none',...
    'Position',[0.3059 0.9471 0.398 0.04949]);

