
%% define function
%this function analyzes pausers, asking for its input, the output of nex2isi
%example: [IPI,pausefreq,rectime]=pausefind2(data,100)

function [pauselength,IPI,pausefreq] = pausefind2(data,minlength)

if nargin <2     minlength=50;
    if nargin < 1 error('No minimum ISI length specified')
    end
end

%data=importdata('*.txt')
%% convert a nexfile to isi and extract the isi column
% nex2isi_multi
isi=data(:,3); %extract isi column of data from the data file generated by
%nex2isi

%% calculates pause parameters
numspikes=length(isi); %calculates total number of spikes
rectime=sum(isi)/1000; % calculates total recording time in seconds
timestamp=cumsum(isi); %calculates individual ISI timestamps

Idx = find(isi>minlength);
pauselength=(isi(Idx)); % length of each pause
eptime=timestamp(Idx); % time of the end of each pause
IPIunc=diff(eptime);
IPIcf=pauselength(2:(end));
IPI=(IPIunc-IPIcf);
IPI(abs(IPI)<0.001)=0 % takes all values if IPI very close to zero and rounds to zero
numpause=length(pauselength)
pausefreq=numpause./rectime

%% and now for the graphics (so we can hold our heads high)

subplot(1,2,1)
hist(IPI); figure(gcf)
title('interpause interval histogram')

subplot(1,2,2)
hist(pauselength); figure(gcf)
title('pause length histogram')



